-- Create products table
CREATE TABLE products (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  brand TEXT NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  original_price DECIMAL(10,2),
  image_url TEXT,
  rating DECIMAL(2,1) DEFAULT 0,
  review_count INTEGER DEFAULT 0,
  skin_types TEXT[] DEFAULT '{}',
  skin_concerns TEXT[] DEFAULT '{}',
  key_ingredients TEXT[] DEFAULT '{}',
  avoid_ingredients TEXT[] DEFAULT '{}',
  ingredient_score INTEGER DEFAULT 0,
  buy_url TEXT,
  store TEXT,
  is_featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read products
CREATE POLICY "Products are viewable by everyone" ON products
  FOR SELECT USING (true);

-- Create indexes
CREATE INDEX idx_products_category ON products(category);
CREATE INDEX idx_products_skin_types ON products USING GIN(skin_types);
CREATE INDEX idx_products_skin_concerns ON products USING GIN(skin_concerns);
CREATE INDEX idx_products_brand ON products(brand);

-- =====================================================
-- CLEANSERS (20 products)
-- =====================================================
INSERT INTO products (brand, name, description, category, price, original_price, rating, review_count, skin_types, skin_concerns, key_ingredients, avoid_ingredients, ingredient_score, store, is_featured) VALUES
('COSRX', 'Low pH Good Morning Gel Cleanser', 'Gentle daily cleanser with tea tree oil and natural BHA for a refreshed complexion', 'cleanser', 12.00, NULL, 4.6, 15234, ARRAY['oily', 'combination', 'sensitive'], ARRAY['acne', 'pores'], ARRAY['tea tree oil', 'bha', 'betaine salicylate'], ARRAY[]::TEXT[], 88, 'Soko Glam', true),
('Beauty of Joseon', 'Radiance Cleansing Balm', 'Makeup melting balm with rice water and soybean oil for glowing skin', 'cleanser', 19.00, 22.00, 4.8, 8921, ARRAY['dry', 'normal', 'combination'], ARRAY['dryness', 'dullness'], ARRAY['rice water', 'soybean oil', 'jojoba oil'], ARRAY[]::TEXT[], 92, 'Olive Young', true),
('Anua', 'Heartleaf Quercetinol Pore Deep Cleansing Foam', 'Deep pore cleansing foam for clear, refined skin', 'cleanser', 16.00, NULL, 4.5, 5432, ARRAY['oily', 'combination'], ARRAY['pores', 'acne'], ARRAY['heartleaf', 'quercetinol', 'salicylic acid'], ARRAY[]::TEXT[], 85, 'YesStyle', false),
('Innisfree', 'Green Tea Amino Hydrating Cleansing Foam', 'Hydrating foam cleanser with Jeju green tea amino acids', 'cleanser', 15.00, NULL, 4.4, 7823, ARRAY['dry', 'normal', 'sensitive'], ARRAY['dryness', 'sensitivity'], ARRAY['green tea', 'amino acids', 'betaine'], ARRAY[]::TEXT[], 86, 'Olive Young', false),
('ROUND LAB', '1025 Dokdo Cleanser', 'Mineral-rich cleanser with deep sea water from Ulleungdo', 'cleanser', 18.00, NULL, 4.7, 9234, ARRAY['oily', 'combination', 'sensitive'], ARRAY['pores', 'hydration'], ARRAY['deep sea water', 'hyaluronic acid', 'panthenol'], ARRAY[]::TEXT[], 91, 'Olive Young', true),
('Sulwhasoo', 'Gentle Cleansing Foam', 'Luxurious foam with Korean medicinal herbs', 'cleanser', 36.00, 42.00, 4.6, 4521, ARRAY['normal', 'dry', 'mature'], ARRAY['aging', 'dullness'], ARRAY['ginseng', 'peony', 'rehmannia'], ARRAY[]::TEXT[], 89, 'Soko Glam', false),
('Heimish', 'All Clean Balm', 'Bestselling cleansing balm that melts away makeup', 'cleanser', 17.00, NULL, 4.7, 12453, ARRAY['all'], ARRAY['dryness', 'sensitivity'], ARRAY['shea butter', 'coconut oil', 'citrus oils'], ARRAY[]::TEXT[], 87, 'YesStyle', true),
('Klairs', 'Gentle Black Deep Cleansing Oil', 'Lightweight cleansing oil with black sesame and botanical oils', 'cleanser', 21.00, NULL, 4.5, 6789, ARRAY['oily', 'combination', 'acne-prone'], ARRAY['acne', 'blackheads'], ARRAY['black sesame oil', 'jojoba oil', 'vitamin e'], ARRAY[]::TEXT[], 88, 'Soko Glam', false),
('Neogen', 'Real Fresh Foam Green Tea', 'Fresh foam cleanser with fermented green tea', 'cleanser', 18.00, 22.00, 4.4, 5432, ARRAY['oily', 'combination'], ARRAY['pores', 'oiliness'], ARRAY['green tea', 'fermented extracts', 'bamboo water'], ARRAY[]::TEXT[], 84, 'Soko Glam', false),
('Isntree', 'Yam Root Vegan Milk Cleanser', 'Creamy vegan cleanser with wild yam root', 'cleanser', 19.00, NULL, 4.6, 4321, ARRAY['dry', 'sensitive', 'normal'], ARRAY['dryness', 'sensitivity'], ARRAY['wild yam', 'oat milk', 'squalane'], ARRAY[]::TEXT[], 93, 'YesStyle', false),
('Etude House', 'Soon Jung pH 6.5 Whip Cleanser', 'Ultra-gentle whip cleanser for sensitive skin', 'cleanser', 12.00, NULL, 4.5, 8765, ARRAY['sensitive', 'dry', 'irritated'], ARRAY['sensitivity', 'redness'], ARRAY['panthenol', 'madecassoside', 'green tea'], ARRAY[]::TEXT[], 90, 'Olive Young', false),
('Dr.G', 'pH Cleansing Gel', 'Dermatologist-developed low pH gel cleanser', 'cleanser', 16.00, NULL, 4.4, 3456, ARRAY['all'], ARRAY['sensitivity', 'acne'], ARRAY['citric acid', 'tea tree', 'centella'], ARRAY[]::TEXT[], 85, 'Olive Young', false),
('Banila Co', 'Clean It Zero Cleansing Balm Original', 'Iconic sherbet-textured cleansing balm', 'cleanser', 23.00, 28.00, 4.8, 21345, ARRAY['all'], ARRAY['dryness', 'makeup removal'], ARRAY['vitamin c', 'vitamin e', 'botanical oils'], ARRAY[]::TEXT[], 86, 'Soko Glam', true),
('SKIN1004', 'Madagascar Centella Light Cleansing Oil', 'Lightweight oil cleanser with centella asiatica', 'cleanser', 18.00, NULL, 4.5, 4567, ARRAY['oily', 'combination', 'sensitive'], ARRAY['acne', 'sensitivity'], ARRAY['centella asiatica', 'jojoba oil', 'sunflower oil'], ARRAY[]::TEXT[], 89, 'YesStyle', false),
('Torriden', 'DIVE-IN Low Molecular Hyaluronic Acid Cleansing Foam', 'Hydrating foam cleanser with 5 types of hyaluronic acid', 'cleanser', 14.00, NULL, 4.6, 5678, ARRAY['dry', 'normal', 'dehydrated'], ARRAY['dryness', 'dehydration'], ARRAY['hyaluronic acid', 'panthenol', 'allantoin'], ARRAY[]::TEXT[], 91, 'Olive Young', false),
('Some By Mi', 'AHA BHA PHA 30 Days Miracle Acne Clear Foam', 'Triple-acid foam cleanser for acne-prone skin', 'cleanser', 12.00, NULL, 4.3, 9876, ARRAY['oily', 'acne-prone'], ARRAY['acne', 'blackheads', 'pores'], ARRAY['aha', 'bha', 'pha', 'tea tree'], ARRAY['sensitive skin']::TEXT[], 79, 'YesStyle', false),
('Missha', 'Super Aqua Cell Renew Snail Cleansing Foam', 'Snail mucin enriched cleansing foam', 'cleanser', 14.00, 18.00, 4.4, 4321, ARRAY['dry', 'normal', 'aging'], ARRAY['aging', 'dryness'], ARRAY['snail mucin', 'baobab oil', 'evening primrose'], ARRAY[]::TEXT[], 85, 'YesStyle', false),
('Laneige', 'Cream Skin Milk Oil Cleanser', 'Cream-to-oil cleanser for a skin barrier boost', 'cleanser', 32.00, NULL, 4.6, 6543, ARRAY['dry', 'normal', 'sensitive'], ARRAY['dryness', 'barrier repair'], ARRAY['milk proteins', 'ceramides', 'oils'], ARRAY[]::TEXT[], 88, 'Soko Glam', false),
('PURITO', 'From Green Cleansing Oil', 'Gentle cleansing oil with olive and sunflower oils', 'cleanser', 19.00, NULL, 4.7, 7654, ARRAY['all'], ARRAY['sensitivity', 'dryness'], ARRAY['olive oil', 'sunflower oil', 'vitamin e'], ARRAY[]::TEXT[], 92, 'YesStyle', false),
('ma:nyo', 'Pure Cleansing Oil', 'Lightweight cleansing oil for daily use', 'cleanser', 22.00, 26.00, 4.5, 8765, ARRAY['oily', 'combination'], ARRAY['blackheads', 'pores'], ARRAY['jojoba oil', 'argan oil', 'vitamin e'], ARRAY[]::TEXT[], 87, 'Olive Young', false),

-- =====================================================
-- TONERS (20 products)
-- =====================================================
('Anua', 'Heartleaf 77% Soothing Toner', 'Calming toner with 77% heartleaf extract for irritated skin', 'toner', 20.00, 25.00, 4.7, 12453, ARRAY['oily', 'sensitive', 'combination'], ARRAY['redness', 'acne', 'pores'], ARRAY['heartleaf', 'niacinamide', 'hyaluronic acid'], ARRAY[]::TEXT[], 95, 'Olive Young', true),
('Isntree', 'Hyaluronic Acid Toner Plus', 'Hydrating toner with 50% hyaluronic acid complex', 'toner', 18.00, NULL, 4.4, 6234, ARRAY['dry', 'normal', 'sensitive'], ARRAY['dryness', 'fine-lines'], ARRAY['hyaluronic acid', 'panthenol', 'allantoin'], ARRAY[]::TEXT[], 90, 'Soko Glam', false),
('COSRX', 'AHA/BHA Clarifying Treatment Toner', 'Exfoliating toner for clear, refined skin', 'toner', 15.00, NULL, 4.3, 4521, ARRAY['oily', 'combination'], ARRAY['acne', 'pores', 'dark-spots'], ARRAY['aha', 'bha', 'apple water'], ARRAY['sensitive skin']::TEXT[], 78, 'YesStyle', false),
('Klairs', 'Supple Preparation Facial Toner', 'Cult-favorite hydrating and soothing toner', 'toner', 22.00, NULL, 4.6, 18765, ARRAY['all'], ARRAY['dryness', 'sensitivity'], ARRAY['hyaluronic acid', 'centella', 'licorice root'], ARRAY[]::TEXT[], 91, 'Soko Glam', true),
('ROUND LAB', '1025 Dokdo Toner', 'Hydrating toner with deep sea water minerals', 'toner', 19.00, NULL, 4.7, 11234, ARRAY['oily', 'combination', 'dehydrated'], ARRAY['hydration', 'pores'], ARRAY['deep sea water', 'hyaluronic acid', 'betaine'], ARRAY[]::TEXT[], 93, 'Olive Young', true),
('Pyunkang Yul', 'Essence Toner', 'Minimalist essence toner with astragalus root', 'toner', 18.00, NULL, 4.5, 9876, ARRAY['sensitive', 'dry', 'normal'], ARRAY['sensitivity', 'hydration'], ARRAY['astragalus root', 'butylene glycol'], ARRAY[]::TEXT[], 94, 'YesStyle', false),
('Laneige', 'Cream Skin Toner & Moisturizer', 'Two-in-one toner and moisturizer for dewy skin', 'toner', 33.00, NULL, 4.6, 14532, ARRAY['dry', 'normal'], ARRAY['dryness', 'dullness'], ARRAY['white tea', 'ceramides', 'amino acids'], ARRAY[]::TEXT[], 88, 'Soko Glam', false),
('Etude House', 'Soon Jung pH 5.5 Relief Toner', 'Ultra-gentle toner for compromised skin barrier', 'toner', 15.00, NULL, 4.5, 7654, ARRAY['sensitive', 'irritated', 'dry'], ARRAY['sensitivity', 'redness'], ARRAY['panthenol', 'madecassoside', 'centella'], ARRAY[]::TEXT[], 92, 'Olive Young', false),
('Innisfree', 'Green Tea Seed Skin', 'Antioxidant-rich toner with Jeju green tea', 'toner', 21.00, 26.00, 4.4, 8765, ARRAY['normal', 'combination', 'oily'], ARRAY['hydration', 'antioxidants'], ARRAY['green tea seed oil', 'green tea extract'], ARRAY[]::TEXT[], 85, 'Olive Young', false),
('Some By Mi', 'AHA BHA PHA 30 Days Miracle Toner', 'Triple-acid toner for acne-prone skin', 'toner', 16.00, NULL, 4.3, 12345, ARRAY['oily', 'acne-prone'], ARRAY['acne', 'pores', 'texture'], ARRAY['aha', 'bha', 'pha', 'tea tree', 'niacinamide'], ARRAY['sensitive skin']::TEXT[], 77, 'YesStyle', false),
('Beauty of Joseon', 'Ginseng Essence Water', 'Anti-aging essence toner with ginseng', 'toner', 19.00, NULL, 4.6, 6543, ARRAY['mature', 'dry', 'normal'], ARRAY['aging', 'dullness', 'firmness'], ARRAY['ginseng', 'niacinamide', 'adenosine'], ARRAY[]::TEXT[], 90, 'Olive Young', false),
('COSRX', 'Full Fit Propolis Synergy Toner', 'Nourishing toner with propolis and honey', 'toner', 23.00, NULL, 4.5, 5432, ARRAY['dry', 'normal', 'dull'], ARRAY['dullness', 'dryness', 'radiance'], ARRAY['propolis', 'honey', 'royal jelly'], ARRAY[]::TEXT[], 89, 'Soko Glam', false),
('Numbuzin', 'No.3 Super Glowing Essence Toner', 'Brightening essence toner with galactomyces', 'toner', 22.00, NULL, 4.7, 8765, ARRAY['all'], ARRAY['dullness', 'dark-spots', 'radiance'], ARRAY['galactomyces', 'niacinamide', 'bifida ferment'], ARRAY[]::TEXT[], 91, 'Olive Young', true),
('Missha', 'Time Revolution Clear Toner', 'Fermented toner for clear, radiant skin', 'toner', 28.00, 34.00, 4.4, 4321, ARRAY['normal', 'combination', 'dull'], ARRAY['dullness', 'texture'], ARRAY['fermented yeast', 'niacinamide', 'hyaluronic acid'], ARRAY[]::TEXT[], 86, 'YesStyle', false),
('SKIN1004', 'Madagascar Centella Toning Toner', 'Soothing toner with pure centella asiatica', 'toner', 17.00, NULL, 4.6, 7654, ARRAY['sensitive', 'oily', 'acne-prone'], ARRAY['redness', 'acne', 'sensitivity'], ARRAY['centella asiatica', 'hyaluronic acid', 'tea tree'], ARRAY[]::TEXT[], 93, 'YesStyle', false),
('I''m From', 'Rice Toner', 'Brightening toner with rice extract from Korea', 'toner', 25.00, NULL, 4.7, 9876, ARRAY['dry', 'dull', 'normal'], ARRAY['dullness', 'dryness', 'radiance'], ARRAY['rice extract', 'niacinamide', 'rice bran'], ARRAY[]::TEXT[], 92, 'Soko Glam', true),
('Benton', 'Aloe BHA Skin Toner', 'Gentle exfoliating toner with aloe and BHA', 'toner', 17.00, NULL, 4.4, 5432, ARRAY['oily', 'combination', 'acne-prone'], ARRAY['acne', 'pores', 'oiliness'], ARRAY['aloe vera', 'bha', 'snail mucin'], ARRAY[]::TEXT[], 87, 'YesStyle', false),
('Neogen', 'Real Ferment Micro Essence', 'Essence toner with 93% fermented ingredients', 'toner', 38.00, 45.00, 4.6, 6789, ARRAY['all'], ARRAY['dullness', 'texture', 'radiance'], ARRAY['bifida ferment', 'rice ferment', 'niacinamide'], ARRAY[]::TEXT[], 90, 'Soko Glam', false),
('Hada Labo', 'Gokujyun Premium Lotion', 'Japanese hydrating toner with 7 types of hyaluronic acid', 'toner', 16.00, NULL, 4.8, 23456, ARRAY['dry', 'dehydrated', 'normal'], ARRAY['dryness', 'dehydration'], ARRAY['hyaluronic acid', 'urea', 'squalane'], ARRAY[]::TEXT[], 94, 'YesStyle', true),
('Mamonde', 'Rose Water Toner', 'Refreshing toner with damask rose water', 'toner', 19.00, 24.00, 4.3, 4567, ARRAY['normal', 'dry', 'sensitive'], ARRAY['hydration', 'soothing'], ARRAY['rose water', 'rose extract', 'hyaluronic acid'], ARRAY[]::TEXT[], 84, 'Soko Glam', false),

-- =====================================================
-- SERUMS & ESSENCES (25 products)
-- =====================================================
('COSRX', 'Advanced Snail 96 Mucin Power Essence', 'Hydrating essence with 96% snail mucin for skin repair', 'serum', 25.00, 28.00, 4.8, 18234, ARRAY['dry', 'normal', 'combination', 'sensitive'], ARRAY['dryness', 'fine-lines', 'dullness', 'scarring'], ARRAY['snail mucin', 'hyaluronic acid', 'allantoin'], ARRAY[]::TEXT[], 94, 'Soko Glam', true),
('Beauty of Joseon', 'Glow Serum: Propolis + Niacinamide', 'Brightening serum with propolis and niacinamide', 'serum', 17.00, NULL, 4.7, 9821, ARRAY['oily', 'combination', 'normal'], ARRAY['dark-spots', 'dullness', 'pores'], ARRAY['propolis', 'niacinamide', 'honey'], ARRAY[]::TEXT[], 91, 'Olive Young', true),
('Torriden', 'DIVE-IN Low Molecule Hyaluronic Acid Serum', 'Deep hydration with 5 types of hyaluronic acid', 'serum', 19.00, 24.00, 4.6, 7892, ARRAY['dry', 'normal', 'sensitive', 'dehydrated'], ARRAY['dryness', 'fine-lines', 'dehydration'], ARRAY['hyaluronic acid', 'panthenol', 'allantoin'], ARRAY[]::TEXT[], 93, 'YesStyle', true),
('SKIN1004', 'Madagascar Centella Ampoule', 'Soothing ampoule with pure centella asiatica', 'serum', 22.00, NULL, 4.5, 6543, ARRAY['sensitive', 'oily', 'combination', 'acne-prone'], ARRAY['redness', 'acne', 'irritation', 'sensitivity'], ARRAY['centella asiatica', 'madecassoside', 'asiaticoside'], ARRAY[]::TEXT[], 89, 'Soko Glam', false),
('The Ordinary', 'Niacinamide 10% + Zinc 1%', 'Pore-minimizing and oil-control serum', 'serum', 12.00, NULL, 4.4, 22341, ARRAY['oily', 'combination', 'acne-prone'], ARRAY['pores', 'acne', 'oiliness'], ARRAY['niacinamide', 'zinc'], ARRAY[]::TEXT[], 86, 'YesStyle', false),
('Klairs', 'Freshly Juiced Vitamin Drop', 'Gentle vitamin C serum for sensitive skin', 'serum', 23.00, NULL, 4.5, 11234, ARRAY['sensitive', 'normal', 'dull'], ARRAY['dark-spots', 'dullness', 'radiance'], ARRAY['vitamin c', 'centella', 'licorice root'], ARRAY[]::TEXT[], 88, 'Soko Glam', false),
('Missha', 'Time Revolution Night Repair Ampoule', 'Anti-aging ampoule with fermented ingredients', 'serum', 45.00, 55.00, 4.6, 8765, ARRAY['mature', 'dry', 'normal'], ARRAY['aging', 'wrinkles', 'firmness'], ARRAY['bifida ferment', 'niacinamide', 'adenosine'], ARRAY[]::TEXT[], 90, 'YesStyle', false),
('COSRX', 'The Vitamin C 23 Serum', 'High-potency vitamin C serum for brightening', 'serum', 25.00, NULL, 4.4, 6543, ARRAY['normal', 'oily', 'combination'], ARRAY['dark-spots', 'dullness', 'uneven-tone'], ARRAY['vitamin c', 'vitamin e', 'hyaluronic acid'], ARRAY['sensitive skin']::TEXT[], 82, 'Soko Glam', false),
('Sulwhasoo', 'First Care Activating Serum', 'Luxurious anti-aging serum with Korean herbs', 'serum', 89.00, 99.00, 4.7, 5432, ARRAY['mature', 'dry', 'normal'], ARRAY['aging', 'dullness', 'firmness'], ARRAY['jaum balancing complex', 'ginseng', 'honey'], ARRAY[]::TEXT[], 91, 'Soko Glam', true),
('Some By Mi', 'Galactomyces Pure Vitamin C Glow Serum', 'Brightening serum with galactomyces and vitamin C', 'serum', 19.00, NULL, 4.3, 7654, ARRAY['oily', 'combination', 'dull'], ARRAY['dullness', 'dark-spots', 'pores'], ARRAY['galactomyces', 'vitamin c', 'niacinamide'], ARRAY[]::TEXT[], 84, 'YesStyle', false),
('Numbuzin', 'No.5 Vitamin-Niacinamide Concentrated Serum', 'Pore-care serum with vitamins and niacinamide', 'serum', 24.00, NULL, 4.6, 9876, ARRAY['oily', 'combination'], ARRAY['pores', 'oiliness', 'dullness'], ARRAY['niacinamide', 'vitamin c', 'vitamin e'], ARRAY[]::TEXT[], 89, 'Olive Young', true),
('I''m From', 'Vitamin Tree Water Gel', 'Lightweight vitamin gel for glowing skin', 'serum', 28.00, NULL, 4.5, 4567, ARRAY['oily', 'combination', 'normal'], ARRAY['dullness', 'hydration', 'radiance'], ARRAY['vitamin tree fruit', 'vitamin c', 'niacinamide'], ARRAY[]::TEXT[], 87, 'Soko Glam', false),
('Benton', 'Snail Bee High Content Essence', 'Healing essence with snail mucin and bee venom', 'serum', 20.00, NULL, 4.6, 12345, ARRAY['acne-prone', 'oily', 'combination'], ARRAY['acne', 'scarring', 'redness'], ARRAY['snail mucin', 'bee venom', 'aloe vera'], ARRAY['bee allergy']::TEXT[], 88, 'YesStyle', false),
('PURITO', 'Centella Unscented Serum', 'Fragrance-free centella serum for sensitive skin', 'serum', 17.00, NULL, 4.7, 8765, ARRAY['sensitive', 'acne-prone', 'irritated'], ARRAY['sensitivity', 'redness', 'acne'], ARRAY['centella asiatica', 'niacinamide', 'panthenol'], ARRAY[]::TEXT[], 94, 'YesStyle', true),
('Rohto Melano', 'CC Vitamin C Essence', 'Japanese vitamin C essence for dark spots', 'serum', 15.00, NULL, 4.5, 15678, ARRAY['all'], ARRAY['dark-spots', 'acne-marks', 'dullness'], ARRAY['vitamin c', 'vitamin e', 'dipotassium glycyrrhizate'], ARRAY[]::TEXT[], 86, 'YesStyle', false),
('Innisfree', 'Green Tea Seed Serum', 'Hydrating serum with Jeju green tea', 'serum', 27.00, 32.00, 4.4, 7654, ARRAY['normal', 'dry', 'combination'], ARRAY['hydration', 'dullness'], ARRAY['green tea seed oil', 'green tea extract', 'hyaluronic acid'], ARRAY[]::TEXT[], 85, 'Olive Young', false),
('Neogen', 'Real Vita C Serum', 'Stable vitamin C serum for brightening', 'serum', 32.00, NULL, 4.5, 5432, ARRAY['normal', 'combination', 'dull'], ARRAY['dark-spots', 'dullness', 'radiance'], ARRAY['vitamin c', 'niacinamide', 'sodium hyaluronate'], ARRAY[]::TEXT[], 87, 'Soko Glam', false),
('ma:nyo', 'Bifida Biome Complex Ampoule', 'Microbiome-balancing ampoule for healthy skin', 'serum', 35.00, 42.00, 4.6, 6789, ARRAY['sensitive', 'dry', 'normal'], ARRAY['sensitivity', 'barrier-repair', 'hydration'], ARRAY['bifida ferment', 'lactobacillus', 'ceramides'], ARRAY[]::TEXT[], 91, 'Olive Young', false),
('Isntree', 'Hyaluronic Acid Airy Sun Stick', 'Hydrating serum with 8 types of hyaluronic acid', 'serum', 23.00, NULL, 4.5, 4321, ARRAY['dry', 'dehydrated', 'normal'], ARRAY['dryness', 'dehydration', 'fine-lines'], ARRAY['hyaluronic acid', 'panthenol', 'betaine'], ARRAY[]::TEXT[], 92, 'YesStyle', false),
('One Thing', 'Centella Asiatica Extract', 'Pure centella extract for calming', 'serum', 12.00, NULL, 4.6, 9876, ARRAY['sensitive', 'acne-prone', 'irritated'], ARRAY['redness', 'sensitivity', 'acne'], ARRAY['centella asiatica'], ARRAY[]::TEXT[], 96, 'YesStyle', false),
('Jumiso', 'All Day Vitamin Brightening & Balancing Serum', 'Multi-vitamin serum for radiant skin', 'serum', 18.00, NULL, 4.5, 5678, ARRAY['all'], ARRAY['dullness', 'dark-spots', 'uneven-tone'], ARRAY['vitamin c', 'vitamin e', 'niacinamide', 'vitamin b5'], ARRAY[]::TEXT[], 88, 'Olive Young', false),
('Haruharu Wonder', 'Black Rice Hyaluronic Serum', 'Antioxidant serum with black rice and hyaluronic acid', 'serum', 24.00, NULL, 4.6, 6543, ARRAY['dry', 'normal', 'mature'], ARRAY['dryness', 'dullness', 'aging'], ARRAY['black rice', 'hyaluronic acid', 'beta glucan'], ARRAY[]::TEXT[], 90, 'YesStyle', false),
('Goodal', 'Green Tangerine Vita C Dark Spot Serum', 'Vitamin C serum with green tangerine', 'serum', 22.00, 28.00, 4.4, 8765, ARRAY['normal', 'combination', 'oily'], ARRAY['dark-spots', 'dullness', 'uneven-tone'], ARRAY['green tangerine', 'vitamin c', 'niacinamide'], ARRAY[]::TEXT[], 85, 'Olive Young', false),
('Dr. Ceuracle', 'Royal Vita Propolis 33 Ampoule', 'Nourishing ampoule with propolis extract', 'serum', 32.00, NULL, 4.7, 4321, ARRAY['dry', 'dull', 'normal'], ARRAY['dullness', 'dryness', 'radiance'], ARRAY['propolis', 'royal jelly', 'honey'], ARRAY[]::TEXT[], 91, 'Soko Glam', false),
('By Wishtrend', 'Pure Vitamin C 21.5 Advanced Serum', 'High-potency vitamin C for advanced brightening', 'serum', 25.00, NULL, 4.3, 7654, ARRAY['normal', 'combination'], ARRAY['dark-spots', 'dullness', 'aging'], ARRAY['vitamin c', 'sea buckthorn', 'sodium hyaluronate'], ARRAY['sensitive skin']::TEXT[], 80, 'YesStyle', false),

-- =====================================================
-- MOISTURIZERS (20 products)
-- =====================================================
('COSRX', 'Oil-Free Ultra-Moisturizing Lotion with Birch Sap', 'Lightweight moisturizer for oily skin', 'moisturizer', 23.00, NULL, 4.5, 8765, ARRAY['oily', 'combination'], ARRAY['oiliness', 'hydration'], ARRAY['birch sap', 'hyaluronic acid', 'willow bark'], ARRAY[]::TEXT[], 87, 'Soko Glam', true),
('Illiyoon', 'Ceramide Ato Concentrate Cream', 'Rich ceramide cream for dry and sensitive skin', 'moisturizer', 25.00, 30.00, 4.8, 11234, ARRAY['dry', 'sensitive', 'normal', 'eczema'], ARRAY['dryness', 'barrier-repair', 'irritation'], ARRAY['ceramide', 'cholesterol', 'fatty acids'], ARRAY[]::TEXT[], 96, 'Olive Young', true),
('Belif', 'The True Cream Aqua Bomb', 'Gel-cream for instant hydration burst', 'moisturizer', 42.00, NULL, 4.6, 9876, ARRAY['oily', 'combination', 'normal'], ARRAY['hydration', 'pores'], ARRAY['lady''s mantle', 'oat extract', 'ceramide'], ARRAY[]::TEXT[], 88, 'Soko Glam', true),
('Klairs', 'Midnight Blue Calming Cream', 'Soothing cream for irritated and sensitive skin', 'moisturizer', 27.00, NULL, 4.6, 7654, ARRAY['sensitive', 'irritated', 'acne-prone'], ARRAY['redness', 'sensitivity', 'acne'], ARRAY['guaiazulene', 'centella', 'chamomile'], ARRAY[]::TEXT[], 91, 'Soko Glam', false),
('Etude House', 'Soon Jung 2x Barrier Intensive Cream', 'Barrier-strengthening cream for sensitive skin', 'moisturizer', 18.00, NULL, 4.7, 12345, ARRAY['sensitive', 'dry', 'irritated'], ARRAY['sensitivity', 'barrier-repair', 'dryness'], ARRAY['panthenol', 'madecassoside', 'squalane'], ARRAY[]::TEXT[], 93, 'Olive Young', true),
('Laneige', 'Water Bank Blue Hyaluronic Cream', 'Hydrating cream with blue hyaluronic acid', 'moisturizer', 38.00, 45.00, 4.5, 8765, ARRAY['dry', 'normal', 'dehydrated'], ARRAY['dryness', 'dehydration', 'dullness'], ARRAY['hyaluronic acid', 'blue hyaluronic acid', 'squalane'], ARRAY[]::TEXT[], 87, 'Soko Glam', false),
('ROUND LAB', '1025 Dokdo Cream', 'Lightweight cream with mineral-rich deep sea water', 'moisturizer', 24.00, NULL, 4.6, 6543, ARRAY['oily', 'combination', 'normal'], ARRAY['hydration', 'balance'], ARRAY['deep sea water', 'hyaluronic acid', 'squalane'], ARRAY[]::TEXT[], 90, 'Olive Young', false),
('Dr. Jart+', 'Ceramidin Cream', 'Intensive barrier repair cream with ceramides', 'moisturizer', 48.00, NULL, 4.7, 14532, ARRAY['dry', 'sensitive', 'damaged'], ARRAY['dryness', 'barrier-repair', 'sensitivity'], ARRAY['ceramides', 'hyaluronic acid', 'shea butter'], ARRAY[]::TEXT[], 92, 'Soko Glam', true),
('PURITO', 'Deep Sea Pure Water Cream', 'Lightweight hydrating cream with sea water', 'moisturizer', 18.00, NULL, 4.5, 5432, ARRAY['oily', 'combination', 'sensitive'], ARRAY['hydration', 'sensitivity'], ARRAY['sea water', 'hyaluronic acid', 'beta glucan'], ARRAY[]::TEXT[], 91, 'YesStyle', false),
('Innisfree', 'Green Tea Seed Cream', 'Antioxidant-rich cream with green tea', 'moisturizer', 30.00, 36.00, 4.4, 7654, ARRAY['normal', 'combination', 'dry'], ARRAY['hydration', 'antioxidants'], ARRAY['green tea seed oil', 'green tea extract', 'squalane'], ARRAY[]::TEXT[], 86, 'Olive Young', false),
('Sulwhasoo', 'Essential Comfort Firming Cream', 'Luxurious firming cream with ginseng', 'moisturizer', 98.00, 120.00, 4.7, 4321, ARRAY['mature', 'dry', 'normal'], ARRAY['aging', 'firmness', 'wrinkles'], ARRAY['ginseng', 'jujube', 'rehmannia'], ARRAY[]::TEXT[], 90, 'Soko Glam', false),
('Some By Mi', 'AHA BHA PHA 30 Days Miracle Cream', 'Exfoliating cream for acne-prone skin', 'moisturizer', 20.00, NULL, 4.2, 9876, ARRAY['oily', 'acne-prone'], ARRAY['acne', 'pores', 'texture'], ARRAY['aha', 'bha', 'pha', 'tea tree'], ARRAY['sensitive skin']::TEXT[], 76, 'YesStyle', false),
('Benton', 'Snail Bee High Content Steam Cream', 'Nourishing cream with snail mucin and bee venom', 'moisturizer', 22.00, NULL, 4.5, 6543, ARRAY['dry', 'normal', 'acne-prone'], ARRAY['scarring', 'hydration', 'acne'], ARRAY['snail mucin', 'bee venom', 'shea butter'], ARRAY['bee allergy']::TEXT[], 87, 'YesStyle', false),
('SKIN1004', 'Madagascar Centella Soothing Cream', 'Calming cream with pure centella', 'moisturizer', 20.00, NULL, 4.6, 5432, ARRAY['sensitive', 'irritated', 'acne-prone'], ARRAY['redness', 'sensitivity', 'acne'], ARRAY['centella asiatica', 'madecassoside', 'panthenol'], ARRAY[]::TEXT[], 92, 'YesStyle', false),
('Holika Holika', 'Good Cera Super Ceramide Cream', 'Ceramide-rich cream for dry skin', 'moisturizer', 24.00, 30.00, 4.4, 4567, ARRAY['dry', 'sensitive', 'normal'], ARRAY['dryness', 'barrier-repair'], ARRAY['ceramide', 'hyaluronic acid', 'shea butter'], ARRAY[]::TEXT[], 88, 'YesStyle', false),
('Pyunkang Yul', 'Nutrition Cream', 'Minimalist nourishing cream for sensitive skin', 'moisturizer', 22.00, NULL, 4.6, 7654, ARRAY['sensitive', 'dry', 'normal'], ARRAY['sensitivity', 'dryness', 'nourishment'], ARRAY['milk vetch root', 'astragalus', 'shea butter'], ARRAY[]::TEXT[], 93, 'YesStyle', false),
('Aestura', 'Atobarrier 365 Cream', 'Dermatologist-developed barrier cream', 'moisturizer', 28.00, NULL, 4.7, 8765, ARRAY['sensitive', 'dry', 'eczema'], ARRAY['sensitivity', 'barrier-repair', 'dryness'], ARRAY['ceramide', 'cholesterol', 'phytosterols'], ARRAY[]::TEXT[], 95, 'Olive Young', true),
('Missha', 'Time Revolution Artemisia Calming Moisture Cream', 'Calming cream with artemisia extract', 'moisturizer', 32.00, 38.00, 4.5, 5678, ARRAY['sensitive', 'combination', 'normal'], ARRAY['sensitivity', 'redness', 'hydration'], ARRAY['artemisia', 'centella', 'hyaluronic acid'], ARRAY[]::TEXT[], 89, 'YesStyle', false),
('I''m From', 'Rice Cream', 'Brightening cream with rice extract', 'moisturizer', 30.00, NULL, 4.6, 6789, ARRAY['dry', 'dull', 'normal'], ARRAY['dullness', 'dryness', 'radiance'], ARRAY['rice extract', 'rice bran oil', 'niacinamide'], ARRAY[]::TEXT[], 90, 'Soko Glam', false),
('ma:nyo', 'Bifida Biome Aqua Barrier Cream', 'Microbiome-balancing moisturizer', 'moisturizer', 32.00, NULL, 4.5, 4321, ARRAY['sensitive', 'dry', 'normal'], ARRAY['sensitivity', 'barrier-repair', 'hydration'], ARRAY['bifida ferment', 'ceramides', 'hyaluronic acid'], ARRAY[]::TEXT[], 91, 'Olive Young', false),

-- =====================================================
-- SUNSCREENS (15 products)
-- =====================================================
('Beauty of Joseon', 'Relief Sun: Rice + Probiotics SPF50+', 'Lightweight sunscreen with rice extract', 'sunscreen', 16.00, NULL, 4.7, 14532, ARRAY['oily', 'combination', 'normal', 'sensitive'], ARRAY['sun-protection'], ARRAY['rice extract', 'probiotics', 'grain ferment'], ARRAY[]::TEXT[], 92, 'Olive Young', true),
('Isntree', 'Hyaluronic Acid Watery Sun Gel SPF50+', 'Hydrating gel sunscreen for dry skin', 'sunscreen', 18.00, 22.00, 4.5, 6789, ARRAY['dry', 'normal', 'sensitive'], ARRAY['sun-protection', 'hydration'], ARRAY['hyaluronic acid', 'centella', 'aloe vera'], ARRAY[]::TEXT[], 90, 'YesStyle', false),
('COSRX', 'Aloe Soothing Sun Cream SPF50+', 'Soothing sunscreen with aloe vera', 'sunscreen', 15.00, NULL, 4.4, 5432, ARRAY['sensitive', 'dry', 'normal'], ARRAY['sun-protection', 'redness'], ARRAY['aloe vera', 'vitamin e', 'chamomile'], ARRAY[]::TEXT[], 85, 'Soko Glam', false),
('Round Lab', 'Birch Juice Moisturizing Sun Cream SPF50+', 'Moisturizing sunscreen with birch juice', 'sunscreen', 18.00, NULL, 4.6, 9876, ARRAY['dry', 'normal', 'dehydrated'], ARRAY['sun-protection', 'hydration'], ARRAY['birch juice', 'hyaluronic acid', 'squalane'], ARRAY[]::TEXT[], 91, 'Olive Young', true),
('Klairs', 'Soft Airy UV Essence SPF50+', 'Lightweight essence-type sunscreen', 'sunscreen', 23.00, NULL, 4.5, 7654, ARRAY['oily', 'combination', 'sensitive'], ARRAY['sun-protection'], ARRAY['centella', 'vitamin e', 'hyaluronic acid'], ARRAY[]::TEXT[], 88, 'Soko Glam', false),
('Anessa', 'Perfect UV Sunscreen Skincare Milk SPF50+', 'Japanese water-resistant sunscreen', 'sunscreen', 35.00, NULL, 4.7, 18765, ARRAY['all', 'active', 'outdoor'], ARRAY['sun-protection', 'water-resistance'], ARRAY['super waterproof', 'hyaluronic acid', 'collagen'], ARRAY[]::TEXT[], 89, 'YesStyle', true),
('Biore', 'UV Aqua Rich Watery Essence SPF50+', 'Iconic Japanese watery sunscreen', 'sunscreen', 15.00, NULL, 4.6, 32456, ARRAY['oily', 'combination', 'normal'], ARRAY['sun-protection'], ARRAY['hyaluronic acid', 'royal jelly', 'citrus extract'], ARRAY[]::TEXT[], 86, 'YesStyle', true),
('PURITO', 'Daily Go-To Sunscreen SPF50+', 'Gentle daily sunscreen for sensitive skin', 'sunscreen', 16.00, NULL, 4.5, 8765, ARRAY['sensitive', 'normal', 'dry'], ARRAY['sun-protection', 'sensitivity'], ARRAY['centella', 'niacinamide', 'hyaluronic acid'], ARRAY[]::TEXT[], 90, 'YesStyle', false),
('Innisfree', 'Daily UV Defense Sunscreen SPF36', 'Lightweight daily sunscreen', 'sunscreen', 18.00, 22.00, 4.3, 5432, ARRAY['all'], ARRAY['sun-protection', 'daily-use'], ARRAY['green tea', 'sunflower oil', 'vitamin e'], ARRAY[]::TEXT[], 84, 'Olive Young', false),
('Dr. Jart+', 'Every Sun Day UV Fluid SPF50+', 'Fluid-type sunscreen for all skin types', 'sunscreen', 32.00, NULL, 4.5, 6543, ARRAY['oily', 'combination', 'normal'], ARRAY['sun-protection'], ARRAY['hyaluronic acid', 'centella', 'vitamin e'], ARRAY[]::TEXT[], 87, 'Soko Glam', false),
('Skin Aqua', 'Tone Up UV Essence SPF50+', 'Lavender-tinted tone-up sunscreen', 'sunscreen', 14.00, NULL, 4.4, 12345, ARRAY['all'], ARRAY['sun-protection', 'tone-up'], ARRAY['hyaluronic acid', 'vitamin c', 'lavender'], ARRAY[]::TEXT[], 85, 'YesStyle', false),
('Krave Beauty', 'The Beet Shield SPF50+', 'Beet-infused sunscreen for antioxidant protection', 'sunscreen', 22.00, NULL, 4.6, 7654, ARRAY['all'], ARRAY['sun-protection', 'antioxidants'], ARRAY['beet extract', 'carrot extract', 'squalane'], ARRAY[]::TEXT[], 91, 'Soko Glam', false),
('SKIN1004', 'Madagascar Centella Air-Fit Sun Cream SPF50+', 'Lightweight centella sunscreen', 'sunscreen', 16.00, NULL, 4.5, 8765, ARRAY['sensitive', 'oily', 'acne-prone'], ARRAY['sun-protection', 'sensitivity'], ARRAY['centella asiatica', 'niacinamide', 'hyaluronic acid'], ARRAY[]::TEXT[], 90, 'YesStyle', false),
('Canmake', 'Mermaid Skin Gel UV SPF50+', 'Japanese primer-sunscreen hybrid', 'sunscreen', 15.00, NULL, 4.4, 9876, ARRAY['oily', 'combination'], ARRAY['sun-protection', 'primer'], ARRAY['hyaluronic acid', 'collagen', 'vitamin c'], ARRAY[]::TEXT[], 83, 'YesStyle', false),
('Missha', 'All Around Safe Block Essence Sun SPF45+', 'Essence-type sunscreen for daily use', 'sunscreen', 14.00, 18.00, 4.3, 5678, ARRAY['all'], ARRAY['sun-protection', 'hydration'], ARRAY['hyaluronic acid', 'centella', 'aloe vera'], ARRAY[]::TEXT[], 84, 'YesStyle', false),

-- =====================================================
-- MASKS & TREATMENTS (15 products)
-- =====================================================
('COSRX', 'Ultimate Nourishing Rice Overnight Spa Mask', 'Overnight hydrating mask with rice extract', 'mask', 18.00, NULL, 4.6, 7654, ARRAY['dry', 'normal', 'dull'], ARRAY['dryness', 'dullness', 'nourishment'], ARRAY['rice extract', 'niacinamide', 'shea butter'], ARRAY[]::TEXT[], 89, 'Soko Glam', true),
('Innisfree', 'Super Volcanic Pore Clay Mask', 'Deep cleansing clay mask for pores', 'mask', 15.00, 18.00, 4.5, 8765, ARRAY['oily', 'combination'], ARRAY['pores', 'oiliness', 'blackheads'], ARRAY['volcanic ash', 'kaolin', 'bentonite'], ARRAY[]::TEXT[], 83, 'Olive Young', false),
('Laneige', 'Water Sleeping Mask', 'Iconic overnight hydrating mask', 'mask', 28.00, NULL, 4.7, 21345, ARRAY['all'], ARRAY['dryness', 'dullness', 'hydration'], ARRAY['sleep-tox', 'hydro ionized mineral water', 'apricot'], ARRAY[]::TEXT[], 88, 'Soko Glam', true),
('I''m From', 'Honey Mask', 'Nourishing wash-off mask with real honey', 'mask', 32.00, NULL, 4.6, 6543, ARRAY['dry', 'dull', 'normal'], ARRAY['dryness', 'dullness', 'nourishment'], ARRAY['honey', 'propolis', 'royal jelly'], ARRAY[]::TEXT[], 91, 'Soko Glam', false),
('Skinfood', 'Black Sugar Mask Wash Off', 'Exfoliating sugar scrub mask', 'mask', 12.00, NULL, 4.4, 9876, ARRAY['oily', 'combination', 'normal'], ARRAY['texture', 'blackheads', 'dullness'], ARRAY['black sugar', 'shea butter', 'lanolin'], ARRAY['sensitive skin']::TEXT[], 79, 'YesStyle', false),
('COSRX', 'Full Fit Propolis Nourishing Magnet Sheet Mask', 'Propolis sheet mask for nourishment', 'mask', 5.00, NULL, 4.5, 4321, ARRAY['dry', 'dull', 'normal'], ARRAY['dryness', 'dullness'], ARRAY['propolis', 'honey', 'royal jelly'], ARRAY[]::TEXT[], 87, 'Soko Glam', false),
('Mediheal', 'N.M.F Intensive Hydrating Mask', 'Cult-favorite hydrating sheet mask', 'mask', 3.00, NULL, 4.6, 34567, ARRAY['dry', 'dehydrated', 'all'], ARRAY['dryness', 'dehydration'], ARRAY['hyaluronic acid', 'ceramides', 'amino acids'], ARRAY[]::TEXT[], 90, 'YesStyle', true),
('Dr. Jart+', 'Dermask Water Jet Vital Hydra Solution', 'Intensive hydrating sheet mask', 'mask', 8.00, NULL, 4.5, 8765, ARRAY['dry', 'dehydrated', 'dull'], ARRAY['dryness', 'dehydration', 'dullness'], ARRAY['hyaluronic acid', 'xylitol', 'algae'], ARRAY[]::TEXT[], 88, 'Soko Glam', false),
('Klairs', 'Midnight Blue Calming Sheet Mask', 'Soothing sheet mask for irritated skin', 'mask', 4.00, NULL, 4.6, 5678, ARRAY['sensitive', 'irritated', 'acne-prone'], ARRAY['redness', 'sensitivity', 'acne'], ARRAY['guaiazulene', 'centella', 'willow bark'], ARRAY[]::TEXT[], 91, 'Soko Glam', false),
('Some By Mi', 'Real Tea Tree Calming Care Mask', 'Tea tree sheet mask for acne-prone skin', 'mask', 3.00, NULL, 4.3, 7654, ARRAY['oily', 'acne-prone'], ARRAY['acne', 'oiliness'], ARRAY['tea tree', 'centella', 'salicylic acid'], ARRAY[]::TEXT[], 82, 'YesStyle', false),
('Sulwhasoo', 'Overnight Vitalizing Mask', 'Luxurious overnight mask with ginseng', 'mask', 60.00, 72.00, 4.7, 3456, ARRAY['mature', 'dry', 'normal'], ARRAY['aging', 'dullness', 'firmness'], ARRAY['ginseng', 'honey', 'jujube'], ARRAY[]::TEXT[], 89, 'Soko Glam', false),
('Heimish', 'All Clean White Clay Mask', 'Purifying clay mask with white clay', 'mask', 16.00, NULL, 4.4, 4567, ARRAY['oily', 'combination'], ARRAY['pores', 'oiliness'], ARRAY['white clay', 'niacinamide', 'centella'], ARRAY[]::TEXT[], 85, 'YesStyle', false),
('Papa Recipe', 'Bombee Honey Mask', 'Honey-infused sheet mask for hydration', 'mask', 4.00, NULL, 4.5, 12345, ARRAY['dry', 'normal', 'dull'], ARRAY['dryness', 'dullness'], ARRAY['honey', 'propolis', 'royal jelly'], ARRAY[]::TEXT[], 86, 'YesStyle', false),
('Benton', 'Snail Bee High Content Mask Pack', 'Sheet mask with snail mucin and bee venom', 'mask', 4.00, NULL, 4.6, 8765, ARRAY['acne-prone', 'scarring', 'dry'], ARRAY['acne', 'scarring', 'hydration'], ARRAY['snail mucin', 'bee venom', 'aloe vera'], ARRAY['bee allergy']::TEXT[], 88, 'YesStyle', false),
('Pyunkang Yul', 'Highly Moisturizing Essence Mask Pack', 'Essence-soaked sheet mask for deep hydration', 'mask', 3.00, NULL, 4.5, 6543, ARRAY['dry', 'sensitive', 'dehydrated'], ARRAY['dryness', 'sensitivity', 'dehydration'], ARRAY['milk vetch root', 'hyaluronic acid', 'glycerin'], ARRAY[]::TEXT[], 92, 'YesStyle', false);
