-- ============================================================================
-- RESET PRODUCTS WITH CLEAN DATA AND REAL IMAGES
-- This will DELETE all existing products and INSERT fresh ones
-- ============================================================================

-- First, delete all existing products
DELETE FROM products;

-- Now insert all 100 products with real Amazon product images
INSERT INTO products (brand, name, category, description, price, currency, raw_inci_text, has_fragrance, base_safety_score, image_url, store, rating, review_count) VALUES

-- CLEANSERS (15)
('COSRX', 'Low pH Good Morning Gel Cleanser', 'cleanser', 'Gentle gel cleanser with tea tree oil', 12.00, 'USD', 'Water, Cocamidopropyl Betaine, Sodium Lauroyl Methyl Isethionate, Sodium Chloride, Polysorbate 20, Styrax Japonicus Branch/Fruit/Leaf Extract, Butylene Glycol, Saccharomyces Ferment, Cryptomeria Japonica Leaf Extract, Nelumbo Nucifera Leaf Extract, Pinus Palustris Leaf Extract, Ulmus Davidiana Root Extract, Oenothera Biennis (Evening Primrose) Flower Extract, Pueraria Lobata Root Extract, Melaleuca Alternifolia (Tea Tree) Leaf Oil, Allantoin, Caprylyl Glycol, Ethylhexylglycerin, Betaine Salicylate, Citric Acid, Disodium EDTA', false, 88, 'https://m.media-amazon.com/images/I/71LxWdJNQML._SL1500_.jpg', 'Soko Glam', 4.5, 2340),

('Krave Beauty', 'Matcha Hemp Hydrating Cleanser', 'cleanser', 'Creamy cleanser with matcha and hemp seed oil', 16.00, 'USD', 'Water, Glycerin, Cocamidopropyl Hydroxysultaine, Coco-Glucoside, Cannabis Sativa Seed Oil, Camellia Sinensis Leaf Powder, Squalane, Oat Kernel Extract, Sodium Hyaluronate, Panthenol, Allantoin, Sodium Chloride, Citric Acid, Ethylhexylglycerin, 1,2-Hexanediol', false, 92, 'https://m.media-amazon.com/images/I/61qK-FcG8TL._SL1500_.jpg', 'Krave Beauty', 4.7, 1890),

('CeraVe', 'Hydrating Facial Cleanser', 'cleanser', 'Non-foaming cleanser with ceramides and hyaluronic acid', 15.99, 'USD', 'Aqua, Glycerin, Cetearyl Alcohol, Phenoxyethanol, Stearyl Alcohol, Cetyl Alcohol, PEG-40 Stearate, Behentrimonium Methosulfate, Glyceryl Stearate, Polysorbate 20, Ethoxydiglycol, Potassium Phosphate, Disodium EDTA, Dipotassium Phosphate, Sodium Lauroyl Lactylate, Ceramide NP, Ceramide AP, Phytosphingosine, Cholesterol, Sodium Hyaluronate, Xanthan Gum, Carbomer, Tocopherol, Ceramide EOP', false, 94, 'https://m.media-amazon.com/images/I/61MXLIxgS7L._SL1500_.jpg', 'Amazon', 4.6, 45230),

('La Roche-Posay', 'Toleriane Hydrating Gentle Cleanser', 'cleanser', 'Hydrating cleanser for sensitive skin', 14.99, 'USD', 'Aqua, Glycerin, Pentaerythrityl Tetraethylhexanoate, Propylene Glycol, Ammonium Polyacryloyldimethyl Taurate, Polysorbate 60, Ceramide NP, Niacinamide, Sodium Chloride, Coco-Betaine, Disodium EDTA', false, 91, 'https://m.media-amazon.com/images/I/61hpIcqEl7L._SL1500_.jpg', 'Ulta', 4.5, 8920),

('Heimish', 'All Clean Balm', 'cleanser', 'Sherbet-textured cleansing balm', 18.00, 'USD', 'Ethylhexyl Palmitate, Diethylhexyl Succinate, Polyethylene, Caprylic/Capric Triglyceride, Cetyl Ethylhexanoate, C12-15 Alkyl Benzoate, Synthetic Wax, Polyglyceryl-10 Dioleate, Polyglyceryl-10 Myristate, Shea Butter, Helianthus Annuus Seed Oil, Tocopheryl Acetate, Citrus Aurantium Bergamia Oil, Citrus Aurantium Dulcis Peel Oil, Pelargonium Graveolens Flower Oil, Jasmine Oil, Rosewood Oil, Oenothera Biennis Oil', true, 82, 'https://m.media-amazon.com/images/I/61kMYrcD4tL._SL1500_.jpg', 'YesStyle', 4.4, 3210),

('Then I Met You', 'Living Cleansing Balm', 'cleanser', 'Luxurious cleansing balm with seaberry and olive oil', 38.00, 'USD', 'Cetyl Ethylhexanoate, Polyglyceryl-10 Dioleate, C12-15 Alkyl Benzoate, Hydrogenated Poly(C6-14 Olefin), Hippophae Rhamnoides Fruit Oil, Olea Europaea Fruit Oil, Tocopherol, Persea Gratissima Oil, Sorbitan Sesquioleate', false, 90, 'https://m.media-amazon.com/images/I/71dS2uxHKPL._SL1500_.jpg', 'Soko Glam', 4.8, 892),

('Banila Co', 'Clean It Zero Cleansing Balm Original', 'cleanser', 'Best-selling sherbet cleanser', 19.00, 'USD', 'Cetyl Ethylhexanoate, PEG-20 Glyceryl Triisostearate, Synthetic Wax, PEG-10 Isostearate, Butylene Glycol, Caprylic/Capric Triglyceride, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Tocopheryl Acetate, Carica Papaya Fruit Extract, Acerola Extract, Phenoxyethanol, Fragrance, Yellow 5, Red 40', true, 80, 'https://m.media-amazon.com/images/I/61gFXJeIr6L._SL1500_.jpg', 'Olive Young', 4.5, 15670),

('Paula''s Choice', 'CLEAR Pore Normalizing Cleanser', 'cleanser', 'Salicylic acid cleanser for acne-prone skin', 18.00, 'USD', 'Water, Sodium Cocoyl Isethionate, Acrylates Copolymer, Glycerin, Sodium Lauroamphoacetate, Salicylic Acid, Butylene Glycol, Polysorbate 20, Sodium Chloride, Allantoin, Disodium EDTA, Sodium Hydroxide', false, 89, 'https://m.media-amazon.com/images/I/71dNJph3SSL._SL1500_.jpg', 'Paula''s Choice', 4.4, 2340),

('Youth To The People', 'Superfood Cleanser', 'cleanser', 'Green juice cleanser with kale and spinach', 36.00, 'USD', 'Aloe Barbadensis Leaf Juice, Aqua, Sodium Cocoyl Glutamate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Brassica Oleracea Acephala Leaf Extract, Spinacia Oleracea Leaf Extract, Camellia Sinensis Leaf Extract, Butylene Glycol, Panthenol, Tocopherol, Sodium Hydroxide, Phenoxyethanol, Ethylhexylglycerin', false, 91, 'https://m.media-amazon.com/images/I/61XM6cXKUdL._SL1500_.jpg', 'Sephora', 4.3, 4560),

('Round Lab', '1025 Dokdo Cleanser', 'cleanser', 'Low pH cleanser with deep sea water', 14.00, 'USD', 'Water, Glycerin, Cocamidopropyl Betaine, Acrylates Copolymer, Sodium Lauroyl Methyl Isethionate, Deep Sea Water, Trehalose, Panthenol, Butylene Glycol, Disodium EDTA, Allantoin, Sodium Hyaluronate, Citric Acid, Ethylhexylglycerin', false, 90, 'https://m.media-amazon.com/images/I/51e0NJHN8fL._SL1500_.jpg', 'Olive Young', 4.6, 2890),

('Innisfree', 'Green Tea Amino Hydrating Cleansing Foam', 'cleanser', 'Hydrating foam cleanser with green tea amino acids', 12.00, 'USD', 'Water, Glycerin, Myristic Acid, Stearic Acid, Potassium Hydroxide, Lauric Acid, Butylene Glycol, Glyceryl Stearate, PEG-100 Stearate, Camellia Sinensis Leaf Extract, Sodium Cocoyl Glutamate, Disodium Cocoyl Glutamate, Carbomer, Disodium EDTA, Phenoxyethanol, Ethylhexylglycerin, Fragrance', true, 85, 'https://m.media-amazon.com/images/I/61UE7M2RAIL._SL1500_.jpg', 'Olive Young', 4.3, 3450),

('Vanicream', 'Gentle Facial Cleanser', 'cleanser', 'Fragrance-free cleanser for sensitive skin', 8.99, 'USD', 'Purified Water, Glycerin, Cocamidopropyl Hydroxysultaine, Sodium Cocoyl Glycinate, Acrylates Copolymer, C12-15 Alkyl Lactate, Panthenol, Sodium Chloride, Potassium Sorbate, Xanthan Gum, Citric Acid, Disodium EDTA', false, 95, 'https://m.media-amazon.com/images/I/61GEGaPbBAL._SL1500_.jpg', 'Amazon', 4.6, 12340),

('Elf', 'Holy Hydration! Makeup Melting Cleansing Balm', 'cleanser', 'Affordable cleansing balm', 10.00, 'USD', 'Cetyl Ethylhexanoate, Caprylic/Capric Triglyceride, Polyglyceryl-10 Diisostearate, PEG-20 Glyceryl Triisostearate, Phenoxyethanol, Simmondsia Chinensis Seed Oil, Tocopheryl Acetate, Macadamia Integrifolia Seed Oil, Ethylhexylglycerin', false, 86, 'https://m.media-amazon.com/images/I/71CJPm0dYQL._SL1500_.jpg', 'Target', 4.2, 5670),

('Beauty of Joseon', 'Radiance Cleansing Balm', 'cleanser', 'Rice bran cleansing balm', 16.00, 'USD', 'Cetyl Ethylhexanoate, Caprylic/Capric Triglyceride, Polyglyceryl-10 Dioleate, C12-15 Alkyl Benzoate, Oryza Sativa Bran Oil, Sorbitan Sesquioleate, Glycine Soja Oil, Oryza Sativa Bran Extract, Camellia Sinensis Leaf Extract, Tocopherol', false, 91, 'https://m.media-amazon.com/images/I/61YWKY5dYZL._SL1500_.jpg', 'Olive Young', 4.7, 4320),

('Stratia', 'Velvet Cleansing Milk', 'cleanser', 'Gentle milky cleanser', 16.00, 'USD', 'Aqua, Glycerin, Isopropyl Myristate, Sorbitan Oleate, Cetyl Alcohol, Glyceryl Stearate, PEG-100 Stearate, Dimethicone, Panthenol, Allantoin, Sodium Hyaluronate, Phenoxyethanol, Ethylhexylglycerin, Disodium EDTA', false, 88, 'https://m.media-amazon.com/images/I/51tFKrXNHcL._SL1500_.jpg', 'Stratia', 4.5, 1230),

-- TONERS (15)
('Klairs', 'Supple Preparation Unscented Toner', 'toner', 'Hydrating toner without essential oils', 22.00, 'USD', 'Water, Butylene Glycol, Dimethyl Sulfone, Betaine, Caprylic/Capric Triglyceride, Natto Gum, Sodium Hyaluronate, Disodium EDTA, Centella Asiatica Extract, Glycyrrhiza Glabra Root Extract, Polyquaternium-51, Chlorophyllin-Copper Complex, Tocopheryl Acetate, Carbomer, Panthenol, Arginine, Luffa Cylindrica Fruit/Leaf/Stem Extract, Beta-Glucan, Althaea Rosea Flower Extract, Allantoin, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Xanthan Gum, Ethylhexylglycerin', false, 93, 'https://m.media-amazon.com/images/I/61gW4qwGBQL._SL1500_.jpg', 'Soko Glam', 4.7, 8920),

('COSRX', 'AHA/BHA Clarifying Treatment Toner', 'toner', 'Exfoliating toner with AHA and BHA', 15.00, 'USD', 'Salix Alba (Willow) Bark Water, Pyrus Malus (Apple) Fruit Water, Butylene Glycol, Glycolic Acid, Betaine Salicylate, 1,2-Hexanediol, Sodium Lactate, Glycerin, Water, Allantoin, Panthenol, Ethyl Hexanediol, Sodium Citrate, Citric Acid', false, 85, 'https://m.media-amazon.com/images/I/61aB5+5oC3L._SL1500_.jpg', 'Ulta', 4.4, 5670),

('Paula''s Choice', '2% BHA Liquid Exfoliant', 'toner', 'Cult-favorite salicylic acid exfoliant', 32.00, 'USD', 'Water, Methylpropanediol, Butylene Glycol, Salicylic Acid, Polysorbate 20, Camellia Oleifera Leaf Extract, Sodium Hydroxide, Tetrasodium EDTA', false, 87, 'https://m.media-amazon.com/images/I/61Zxb7CfzPL._SL1500_.jpg', 'Paula''s Choice', 4.6, 23450),

('Isntree', 'Hyaluronic Acid Toner', 'toner', 'Multi-molecular hyaluronic acid toner', 18.00, 'USD', 'Water, Butylene Glycol, Glycerin, 1,2-Hexanediol, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Hyaluronic Acid, Sodium Acetylated Hyaluronate, Hydrolyzed Sodium Hyaluronate, Panthenol, Allantoin, Betaine, Carbomer, Tromethamine', false, 94, 'https://m.media-amazon.com/images/I/51qZdRBvORL._SL1500_.jpg', 'YesStyle', 4.7, 3210),

('Pyunkang Yul', 'Essence Toner', 'toner', 'Minimal ingredient essence toner', 13.00, 'USD', 'Astragalus Membranaceus Root Extract, Butylene Glycol, Glycerin, Glyceryl Glucoside, Arginine, Carbomer, Allantoin, Hydroxyethylcellulose, Dipotassium Glycyrrhizate, Disodium EDTA, Ethylhexylglycerin, Hydrogenated Lecithin, 1,2-Hexanediol', false, 95, 'https://m.media-amazon.com/images/I/61PeyPkDyVL._SL1500_.jpg', 'Soko Glam', 4.6, 4560),

('Hada Labo', 'Gokujyun Premium Lotion', 'toner', 'Japanese hydrating lotion with 5 types of HA', 15.00, 'USD', 'Water, Butylene Glycol, Glycerin, PPG-10 Methyl Glucose Ether, Hydroxyethyl Urea, Sodium Acetylated Hyaluronate, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Sodium Hyaluronate Crosspolymer, Apricot Kernel Extract, Ammonium Acryloyldimethyltaurate/VP Copolymer, Arginine, Triethyl Citrate, Disodium Succinate, Succinic Acid, Disodium EDTA, Methylparaben, Propylparaben', false, 89, 'https://m.media-amazon.com/images/I/41bJxaLirkL._SL1000_.jpg', 'Amazon', 4.7, 12340),

('Some By Mi', 'AHA BHA PHA 30 Days Miracle Toner', 'toner', 'Triple exfoliating toner', 16.00, 'USD', 'Water, Butylene Glycol, Dipropylene Glycol, Glycerin, Niacinamide, Melaleuca Alternifolia Leaf Water, Glycolic Acid, Salicylic Acid, Gluconolactone, Centella Asiatica Extract, Sodium Hyaluronate, Allantoin, Panthenol, Adenosine, Madecassoside, Xanthan Gum, Ethylhexylglycerin, 1,2-Hexanediol', false, 82, 'https://m.media-amazon.com/images/I/71HW9aCF-QL._SL1500_.jpg', 'Olive Young', 4.3, 8970),

('The Ordinary', 'Glycolic Acid 7% Toning Solution', 'toner', 'Exfoliating toner with glycolic acid', 8.70, 'USD', 'Aqua, Glycolic Acid, Rosa Damascena Flower Water, Centaurea Cyanus Flower Water, Aloe Barbadensis Leaf Water, Propanediol, Glycerin, Triethanolamine, Aminomethyl Propanol, Panax Ginseng Root Extract, Tasmannia Lanceolata Fruit/Leaf Extract, Aspartic Acid, Alanine, Glycine, Serine, Valine, Isoleucine, Proline, Threonine, Histidine, Phenylalanine, Glutamic Acid, Arginine, PCA, Sodium PCA, Sodium Lactate, Sodium Hyaluronate Crosspolymer, Sodium Hyaluronate, Polysorbate 20, Trisodium Ethylenediamine Disuccinate, Potassium Sorbate, Sodium Benzoate, 1,2-Hexanediol, Caprylyl Glycol', false, 83, 'https://m.media-amazon.com/images/I/51R6xXBPGQL._SL1500_.jpg', 'Sephora', 4.4, 15670),

('Laneige', 'Cream Skin Refiner', 'toner', 'Cream-in-toner hybrid', 33.00, 'USD', 'Water, Glycerin, Propanediol, Alcohol, Niacinamide, Squalane, Butylene Glycol, Pentylene Glycol, Trehalose, Caprylic/Capric Triglyceride, Glyceryl Stearate, PEG-100 Stearate, Amino Acid Complex, Ceramide NP, Sodium Hyaluronate, Hydrogenated Lecithin, Cholesterol, Cetearyl Alcohol, Carbomer, Disodium EDTA, Ethylhexylglycerin, Fragrance', true, 84, 'https://m.media-amazon.com/images/I/51zFLpWGP-L._SL1500_.jpg', 'Sephora', 4.5, 6780),

('Kikumasamune', 'High Moist Lotion', 'toner', 'Japanese sake toner in jumbo size', 14.00, 'USD', 'Water, Butylene Glycol, Glycerin, Dipropylene Glycol, Sake, Glyceryl Glucoside, Glutamic Acid, Arginine, Leucine, Ceramide 3, Arbutin, Placenta Extract, Sodium Hyaluronate, Disodium EDTA, Fragrance, Methylparaben', true, 86, 'https://m.media-amazon.com/images/I/61ByNFLCPeL._SL1500_.jpg', 'Amazon', 4.5, 7890),

('Pixi', 'Glow Tonic', 'toner', '5% glycolic acid toner', 29.00, 'USD', 'Aqua, Aloe Barbadensis Leaf Juice, Glycolic Acid, Hamamelis Virginiana Water, Aesculus Hippocastanum Seed Extract, Ficus Carica Fruit Extract, Punica Granatum Extract, Glycerin, Arginine, Panax Ginseng Root Extract, Sodium Hyaluronate, Butylene Glycol, Polysorbate 20, Benzalkonium Chloride, Potassium Sorbate, Sodium Benzoate, Hexylene Glycol, Fragrance', true, 82, 'https://m.media-amazon.com/images/I/71P8WnKCBxL._SL1500_.jpg', 'Target', 4.3, 8900),

('Naturie', 'Hatomugi Skin Conditioner', 'toner', 'Japanese coix seed toner', 10.00, 'USD', 'Water, Butylene Glycol, Glycerin, Coix Lacryma-Jobi Ma-Yuen Seed Extract, Styrene/VP Copolymer, Ethanol, Citric Acid, Sodium Citrate, Methylparaben', false, 91, 'https://m.media-amazon.com/images/I/71kT+m2c5JL._SL1500_.jpg', 'Amazon', 4.4, 5670),

('Be Plain', 'Bamboo Hydrating Toner', 'toner', 'Hydrating toner with bamboo water', 16.00, 'USD', 'Bambusa Vulgaris Water, Butylene Glycol, Glycerin, 1,2-Hexanediol, Betaine, Centella Asiatica Extract, Panthenol, Sodium Hyaluronate, Trehalose, Allantoin, Disodium EDTA, Adenosine, Xanthan Gum', false, 93, 'https://m.media-amazon.com/images/I/61HrMT0ivVL._SL1500_.jpg', 'Olive Young', 4.6, 2340),

('SKIN1004', 'Madagascar Centella Toning Toner', 'toner', 'Centella-based calming toner', 20.00, 'USD', 'Centella Asiatica Extract, Butylene Glycol, Glycerin, 1,2-Hexanediol, Sodium Hyaluronate, Asiaticoside, Madecassic Acid, Asiatic Acid, Allantoin, Panthenol, Adenosine, Trehalose, Disodium EDTA', false, 94, 'https://m.media-amazon.com/images/I/61PEgYKT6LL._SL1500_.jpg', 'Olive Young', 4.7, 5670),

('Keep Cool', 'Soothe Bamboo Toner', 'toner', 'Calming bamboo toner', 18.00, 'USD', 'Bambusa Vulgaris Water, Glycerin, Butylene Glycol, 1,2-Hexanediol, Allantoin, Sodium Hyaluronate, Panthenol, Centella Asiatica Extract, Glycyrrhiza Glabra Root Extract, Dipotassium Glycyrrhizate, Madecassoside, Adenosine, Xanthan Gum, Disodium EDTA', false, 93, 'https://m.media-amazon.com/images/I/61qrqvY2wIL._SL1200_.jpg', 'YesStyle', 4.5, 2110),

-- SERUMS/ESSENCES (20)
('COSRX', 'Advanced Snail 96 Mucin Power Essence', 'essence', 'Snail mucin essence for hydration and repair', 22.00, 'USD', 'Snail Secretion Filtrate, Betaine, Butylene Glycol, 1,2-Hexanediol, Sodium Polyacrylate, Phenoxyethanol, Sodium Hyaluronate, Allantoin, Ethyl Hexanediol, Carbomer, Panthenol, Arginine, Adenosine', false, 92, 'https://m.media-amazon.com/images/I/61rCy3F2zTL._SL1500_.jpg', 'Soko Glam', 4.6, 34560),

('The Ordinary', 'Niacinamide 10% + Zinc 1%', 'serum', 'Pore-minimizing niacinamide serum', 6.00, 'USD', 'Aqua, Niacinamide, Pentylene Glycol, Zinc PCA, Dimethyl Isosorbide, Tamarindus Indica Seed Gum, Xanthan Gum, Isoceteth-20, Ethoxydiglycol, Phenoxyethanol, Chlorphenesin', false, 90, 'https://m.media-amazon.com/images/I/61W65lFNNTL._SL1500_.jpg', 'Sephora', 4.4, 67890),

('Good Molecules', 'Hyaluronic Acid Serum', 'serum', 'Affordable hyaluronic acid serum', 6.00, 'USD', 'Water, Glycerin, Propanediol, Sodium Hyaluronate, Sodium Hyaluronate Crosspolymer, Hydrolyzed Sodium Hyaluronate, Panthenol, Cassia Angustifolia Seed Polysaccharide, Allantoin, Citric Acid, Sodium Citrate, Sodium Benzoate, Ethylhexylglycerin, Phenoxyethanol', false, 94, 'https://m.media-amazon.com/images/I/71pxtoYMYzL._SL1500_.jpg', 'Ulta', 4.5, 5670),

('Beauty of Joseon', 'Glow Serum: Propolis + Niacinamide', 'serum', 'Propolis and niacinamide brightening serum', 17.00, 'USD', 'Propolis Extract, Glycerin, Butylene Glycol, Water, Niacinamide, 1,2-Hexanediol, Sodium Polyacrylate, Xanthan Gum, Panthenol, Allantoin, Adenosine, Disodium EDTA', false, 93, 'https://m.media-amazon.com/images/I/61m0BTDP5FL._SL1500_.jpg', 'Olive Young', 4.8, 8970),

('Paula''s Choice', 'C15 Super Booster', 'serum', '15% vitamin C serum', 52.00, 'USD', 'Water, Ascorbic Acid, Butylene Glycol, Ethoxydiglycol, Glycerin, Pentylene Glycol, Tocopherol, Sodium Hyaluronate, Bisabolol, Panthenol, Ferulic Acid, Polyacrylate-13, Polyisobutene, Polysorbate 20, Trisodium Ethylenediamine Disuccinate, Camellia Sinensis Leaf Extract', false, 88, 'https://m.media-amazon.com/images/I/51kIcLPLBHL._SL1500_.jpg', 'Paula''s Choice', 4.5, 4560),

('IUNIK', 'Propolis Vitamin Synergy Serum', 'serum', 'Propolis and sea buckthorn serum', 18.00, 'USD', 'Hippophae Rhamnoides Water, Propolis Extract, Glycerin, Butylene Glycol, 1,2-Hexanediol, Niacinamide, Sodium Hyaluronate, Panthenol, Allantoin, Adenosine, Centella Asiatica Extract, Sodium Ascorbyl Phosphate, Tocopheryl Acetate, Arginine, Carbomer, Xanthan Gum', false, 92, 'https://m.media-amazon.com/images/I/51O+hGfPaEL._SL1500_.jpg', 'YesStyle', 4.6, 3450),

('Purito', 'Centella Unscented Serum', 'serum', 'Fragrance-free centella serum', 15.00, 'USD', 'Water, Centella Asiatica Extract, Glycerin, Dipropylene Glycol, Niacinamide, Butylene Glycol, 1,2-Hexanediol, Betaine, Asiaticoside, Madecassic Acid, Asiatic Acid, Madecassoside, Sodium Hyaluronate, Allantoin, Arginine, Panthenol, Carbomer, Adenosine', false, 95, 'https://m.media-amazon.com/images/I/61x7ZdF9FKL._SL1500_.jpg', 'Soko Glam', 4.7, 5670),

('Timeless', 'Vitamin C + E Ferulic Acid Serum', 'serum', 'Potent 20% vitamin C serum', 24.95, 'USD', 'Water, Ethoxydiglycol, L-Ascorbic Acid, Propylene Glycol, Alpha Tocopherol, Polysorbate 80, Panthenol, Ferulic Acid, Sodium Hyaluronate, Benzylalcohol, Dehydroacetic Acid', false, 86, 'https://m.media-amazon.com/images/I/61c+9nCBVpL._SL1500_.jpg', 'Amazon', 4.4, 8970),

('Skinceuticals', 'C E Ferulic', 'serum', 'Luxury vitamin C serum', 182.00, 'USD', 'Water, Ethoxydiglycol, Ascorbic Acid, Glycerin, Propylene Glycol, Laureth-23, Phenoxyethanol, Tocopherol, Triethanolamine, Ferulic Acid, Sodium Hyaluronate, Panthenol', false, 88, 'https://m.media-amazon.com/images/I/51p-ZkZRMuL._SL1500_.jpg', 'Dermstore', 4.6, 12340),

('The Ordinary', 'Hyaluronic Acid 2% + B5', 'serum', 'Multi-weight hyaluronic acid serum', 7.70, 'USD', 'Aqua, Sodium Hyaluronate, Sodium Hyaluronate Crosspolymer, Panthenol, Ahnfeltia Concinna Extract, Glycerin, Pentylene Glycol, Propanediol, Polyacrylate Crosspolymer-6, PPG-26-Buteth-26, PEG-40 Hydrogenated Castor Oil, Trisodium Ethylenediamine Disuccinate, Citric Acid, Ethoxydiglycol, Phenoxyethanol, Chlorphenesin', false, 92, 'https://m.media-amazon.com/images/I/61BYuMDlG9L._SL1500_.jpg', 'Sephora', 4.5, 34560),

('Missha', 'Time Revolution First Treatment Essence', 'essence', 'Fermented yeast essence', 37.00, 'USD', 'Saccharomyces Ferment Filtrate, Niacinamide, Bifida Ferment Lysate, Glycerin, Propanediol, Polyglycerin-3, Sodium Hyaluronate, Panthenol, Adenosine, Disodium EDTA, Polyquaternium-51, 1,2-Hexanediol, Butylene Glycol', false, 91, 'https://m.media-amazon.com/images/I/51YJJ+FKBRL._SL1500_.jpg', 'YesStyle', 4.5, 6780),

('SK-II', 'Facial Treatment Essence', 'essence', 'Iconic pitera essence', 185.00, 'USD', 'Galactomyces Ferment Filtrate, Butylene Glycol, Pentylene Glycol, Water, Sodium Benzoate, Methylparaben, Sorbic Acid', false, 89, 'https://m.media-amazon.com/images/I/61WKFCRFQ1L._SL1500_.jpg', 'Sephora', 4.4, 8970),

('Rohto Melano CC', 'Vitamin C Essence', 'essence', 'Japanese vitamin C spot treatment', 14.00, 'USD', 'Ascorbic Acid, Tocopheryl Acetate, Dipotassium Glycyrrhizate, Isopropylmethylphenol, Thickeners, Butylene Glycol, Edetate, Perfume', true, 84, 'https://m.media-amazon.com/images/I/41W-4BuVnvL._SL1200_.jpg', 'Amazon', 4.3, 12340),

('Tiam', 'Vita B3 Source', 'serum', '10% niacinamide serum', 14.00, 'USD', 'Water, Niacinamide, Butylene Glycol, Glycerin, 1,2-Hexanediol, Betaine, Panthenol, Sodium Hyaluronate, Allantoin, Disodium EDTA, Carbomer, Arginine, Ethylhexylglycerin', false, 92, 'https://m.media-amazon.com/images/I/51yx3cQ7rKL._SL1500_.jpg', 'YesStyle', 4.6, 2340),

('By Wishtrend', 'Pure Vitamin C 21.5 Advanced Serum', 'serum', 'Potent vitamin C serum', 23.00, 'USD', 'Hippophae Rhamnoides Water, Ascorbic Acid, Sodium Lactate, Citrus Limon Fruit Extract, Sodium Hyaluronate, Cassia Obtusifolia Seed Extract, Allantoin, Panthenol', false, 85, 'https://m.media-amazon.com/images/I/51n2AwcSQqL._SL1500_.jpg', 'Soko Glam', 4.4, 3450),

('Drunk Elephant', 'C-Firma Fresh Day Serum', 'serum', 'Potent vitamin C serum with ferulic acid', 84.00, 'USD', 'Water, Ascorbic Acid, Glycerin, Dicaprylyl Carbonate, Squalane, Silica, Sodium Hyaluronate Crosspolymer, Tocopherol, Ferulic Acid, Sodium Hyaluronate, Camellia Sinensis Leaf Extract, Vitis Vinifera Juice Extract, Punica Granatum Extract, Sodium Citrate, Xanthan Gum, Phenoxyethanol, Triethoxycaprylylsilane', false, 88, 'https://m.media-amazon.com/images/I/61KSJI3+9IL._SL1500_.jpg', 'Sephora', 4.3, 5670),

('One Thing', 'Centella Asiatica Extract', 'essence', 'Single-ingredient centella essence', 11.00, 'USD', 'Centella Asiatica Extract', false, 98, 'https://m.media-amazon.com/images/I/51bqJC7MjtL._SL1500_.jpg', 'Olive Young', 4.7, 4560),

('Numbuzin', 'No. 3 Super Glowing Essence Toner', 'essence', 'Bifida and galactomyces essence', 20.00, 'USD', 'Water, Bifida Ferment Lysate, Galactomyces Ferment Filtrate, Glycerin, Niacinamide, 1,2-Hexanediol, Butylene Glycol, Sodium Hyaluronate, Panthenol, Allantoin, Adenosine, Carbomer, Arginine, Disodium EDTA, Ethylhexylglycerin', false, 92, 'https://m.media-amazon.com/images/I/61WR7Q0WDRL._SL1500_.jpg', 'Olive Young', 4.8, 6780),

('Anua', 'Heartleaf 77% Soothing Toner', 'essence', 'Calming heartleaf toner', 18.00, 'USD', 'Houttuynia Cordata Extract, Propanediol, Glycerin, 1,2-Hexanediol, Butylene Glycol, Water, Sodium Hyaluronate, Allantoin, Panthenol, Betaine, Madecassoside, Carbomer, Arginine, Disodium EDTA, Ethylhexylglycerin', false, 94, 'https://m.media-amazon.com/images/I/51wKLIvJ7JL._SL1500_.jpg', 'Olive Young', 4.7, 8970),

('Torriden', 'Dive-In Low Molecular Hyaluronic Acid Serum', 'serum', '5 types of hyaluronic acid serum', 19.00, 'USD', 'Water, Glycerin, Propanediol, Sodium Hyaluronate, Hydrolyzed Hyaluronic Acid, Hyaluronic Acid, Sodium Acetylated Hyaluronate, Hydrolyzed Sodium Hyaluronate, Panthenol, Allantoin, Betaine, 1,2-Hexanediol, Carbomer, Arginine, Ethylhexylglycerin', false, 95, 'https://m.media-amazon.com/images/I/61qQv7v6URL._SL1500_.jpg', 'Olive Young', 4.8, 7890),

-- MOISTURIZERS (20)
('COSRX', 'Oil-Free Ultra-Moisturizing Lotion', 'moisturizer', 'Lightweight birch sap lotion', 21.00, 'USD', 'Betula Platyphylla Japonica Juice, Glycerin, Dimethicone, Betaine, Cetearyl Olivate, Sorbitan Olivate, 1,2-Hexanediol, Sodium Hyaluronate, Sodium PCA, Ethylhexylglycerin, Panthenol, Allantoin, Xanthan Gum, Adenosine, Butylene Glycol, Carbomer, Arginine', false, 91, 'https://m.media-amazon.com/images/I/61pUq2GKXJL._SL1500_.jpg', 'Soko Glam', 4.5, 5670),

('CeraVe', 'PM Facial Moisturizing Lotion', 'moisturizer', 'Niacinamide moisturizer with ceramides', 16.99, 'USD', 'Aqua, Glycerin, Caprylic/Capric Triglyceride, Niacinamide, Cetearyl Alcohol, Phospholipids, Ceramide NP, Ceramide AP, Ceramide EOP, Carbomer, Dimethicone, Petrolatum, Ceteareth-20, Behentrimonium Methosulfate, Sodium Hyaluronate, Sodium Lauroyl Lactylate, Cholesterol, Phenoxyethanol, Disodium EDTA, Phytosphingosine, Xanthan Gum, Tocopherol', false, 93, 'https://m.media-amazon.com/images/I/61S7BrCBj7L._SL1500_.jpg', 'Amazon', 4.6, 67890),

('Neutrogena', 'Hydro Boost Water Gel', 'moisturizer', 'Lightweight hyaluronic acid gel cream', 19.97, 'USD', 'Water, Dimethicone, Glycerin, Dimethicone/Vinyl Dimethicone Crosspolymer, Phenoxyethanol, Polyacrylamide, Sodium Hyaluronate, Cetearyl Olivate, Sorbitan Olivate, Dimethiconol, C13-14 Isoparaffin, Chlorphenesin, Carbomer, Laureth-7, Sodium Hydroxide, Ethylhexylglycerin, Blue 1', false, 87, 'https://m.media-amazon.com/images/I/716g06aOBTL._SL1500_.jpg', 'Target', 4.4, 23450),

('Illiyoon', 'Ceramide Ato Concentrate Cream', 'moisturizer', 'Rich ceramide cream for dry skin', 20.00, 'USD', 'Water, Butylene Glycol, Glycerin, Cetyl Ethylhexanoate, Caprylic/Capric Triglyceride, Squalane, 1,2-Hexanediol, Ceramide NP, Cholesterol, Shea Butter, Glyceryl Stearate, Behenyl Alcohol, Glyceryl Caprylate, Xanthan Gum, Carbomer, Disodium EDTA, Panthenol, Allantoin, Tocopheryl Acetate', false, 94, 'https://m.media-amazon.com/images/I/61sVgFLfXEL._SL1500_.jpg', 'Olive Young', 4.7, 8970),

('Kiehl''s', 'Ultra Facial Cream', 'moisturizer', 'Classic hydrating cream', 35.00, 'USD', 'Aqua, Glycerin, Cyclohexasiloxane, Squalane, Bis-PEG-18 Methyl Ether Dimethyl Silane, Sucrose Stearate, Stearyl Alcohol, PEG-8 Stearate, Myristyl Myristate, Pentaerythrityl Tetraethylhexanoate, Prunus Armeniaca Kernel Oil, Phenoxyethanol, Persea Gratissima Oil, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Carbomer, Tocopherol, Sodium Hydroxide, Disodium EDTA, Prunus Amygdalus Dulcis Oil', false, 85, 'https://m.media-amazon.com/images/I/61Bm8FNQ-5L._SL1500_.jpg', 'Sephora', 4.5, 12340),

('La Roche-Posay', 'Toleriane Double Repair Face Moisturizer', 'moisturizer', 'Ceramide moisturizer with niacinamide', 22.99, 'USD', 'Aqua, Glycerin, Dimethicone, Isocetyl Stearate, Niacinamide, Butylene Glycol, Propanediol, Cetearyl Alcohol, PEG-100 Stearate, Glyceryl Stearate, Ceramide NP, Dimethiconol, Sodium Hyaluronate, Xanthan Gum, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Tocopherol, Sodium Stearoyl Glutamate, Sodium Hydroxide, Disodium EDTA, Phenoxyethanol, Chlorphenesin', false, 91, 'https://m.media-amazon.com/images/I/61lCn4Vg-HL._SL1500_.jpg', 'Ulta', 4.6, 15670),

('Belif', 'The True Cream Aqua Bomb', 'moisturizer', 'Lightweight gel-cream moisturizer', 42.00, 'USD', 'Water, Dipropylene Glycol, Glycerin, Glycereth-26, Methylpropanediol, Dimethicone, 1,2-Hexanediol, Pentaerythrityl Tetraisostearate, Ammonium Acryloyldimethyltaurate/VP Copolymer, Glyceryl Stearate SE, Cetyl Alcohol, Panthenol, Hydrogenated Polyisobutene, Triethylhexanoin, Adenosine, Disodium EDTA, Fragrance', true, 86, 'https://m.media-amazon.com/images/I/51NyN+rTjZL._SL1500_.jpg', 'Sephora', 4.4, 8970),

('Etude House', 'Soon Jung 2x Barrier Intensive Cream', 'moisturizer', 'Fragrance-free barrier cream', 14.00, 'USD', 'Water, Glycerin, Propanediol, Pentaerythrityl Tetraethylhexanoate, Panthenol, Butylene Glycol, Madecassoside, Camellia Sinensis Leaf Extract, Glyceryl Stearate SE, Cetearyl Alcohol, Hydrogenated Lecithin, Glyceryl Stearate, Stearic Acid, Arachidyl Alcohol, Behenyl Alcohol, Arachidyl Glucoside, Carbomer, Ethylhexylglycerin, Disodium EDTA, Adenosine', false, 93, 'https://m.media-amazon.com/images/I/61hMvdpZURL._SL1500_.jpg', 'Olive Young', 4.7, 6780),

('First Aid Beauty', 'Ultra Repair Cream', 'moisturizer', 'Rich cream for very dry skin', 38.00, 'USD', 'Water, Stearic Acid, Glycerin, C12-15 Alkyl Benzoate, Caprylic/Capric Triglyceride, Glyceryl Stearate SE, Glyceryl Stearate, Cetearyl Alcohol, Butyrospermum Parkii Butter, Squalane, Dimethicone, Phenoxyethanol, Allantoin, Sodium Hydroxide, Xanthan Gum, Caprylyl Glycol, Disodium EDTA, Chrysanthemum Parthenium Extract, Ceramide NP, Eucalyptus Globulus Leaf Extract', false, 90, 'https://m.media-amazon.com/images/I/61x9vVyGPsL._SL1500_.jpg', 'Sephora', 4.5, 23450),

('Peter Thomas Roth', 'Water Drench Hyaluronic Cloud Cream', 'moisturizer', 'Hyaluronic acid rich cream', 52.00, 'USD', 'Water, Glycerin, Pentylene Glycol, Squalane, Polysilicone-11, Glyceryl Stearate, PEG-100 Stearate, Sodium Hyaluronate, Cetyl Alcohol, Hyaluronic Acid, Ceramide NP, Camellia Sinensis Leaf Extract, Caffeine, Allantoin, Carbomer, Phenoxyethanol, Ethylhexylglycerin, Disodium EDTA, Fragrance', true, 87, 'https://m.media-amazon.com/images/I/61NE4xjzShL._SL1500_.jpg', 'Sephora', 4.4, 5670),

('Tatcha', 'The Dewy Skin Cream', 'moisturizer', 'Luxurious Japanese moisturizer', 69.00, 'USD', 'Water, Glycerin, Squalane, Dimethicone, Dipropylene Glycol, Cetyl Ethylhexanoate, Butylene Glycol, Saccharomyces/Camellia Sinensis Leaf/Cladosiphon Okamuranus/Rice Ferment Filtrate, Camellia Japonica Seed Oil, Sodium Hyaluronate, Chondrus Crispus Extract, Algae Extract, Tocopherol, Oryza Sativa Bran Extract, Ceramide NP, Fragrance', true, 87, 'https://m.media-amazon.com/images/I/51eW8jxYHIL._SL1500_.jpg', 'Sephora', 4.5, 8970),

('Drunk Elephant', 'Protini Polypeptide Cream', 'moisturizer', 'Peptide-rich moisturizer', 68.00, 'USD', 'Water, Dicaprylyl Carbonate, Glycerin, Cetearyl Alcohol, Cetearyl Glucoside, Sodium Hyaluronate, Pygmy Waterlily Stem Cell Extract, Acetyl Glutamine, SH-Oligopeptide-1, SH-Oligopeptide-2, SH-Polypeptide-1, SH-Polypeptide-9, SH-Polypeptide-11, Copper Lysinate/Prolinate, Phospholipids, Sclerocarya Birrea Seed Oil, Helianthus Annuus Seed Oil, Sodium Hyaluronate Crosspolymer, Soybean Glycerides, Tocopherol', false, 90, 'https://m.media-amazon.com/images/I/61JRl-a0OkL._SL1500_.jpg', 'Sephora', 4.3, 6780),

('The Ordinary', 'Natural Moisturizing Factors + HA', 'moisturizer', 'Affordable no-frills moisturizer', 7.90, 'USD', 'Aqua, Caprylic/Capric Triglyceride, Cetyl Alcohol, Propanediol, Stearyl Alcohol, Glycerin, Sodium Hyaluronate, Arginine, Aspartic Acid, Glycine, Alanine, Serine, Valine, Isoleucine, Proline, Threonine, Histidine, Phenylalanine, Glucose, Maltose, Fructose, Trehalose, Sodium PCA, PCA, Sodium Lactate, Urea, Allantoin, Sodium Hyaluronate Crosspolymer, Phospholipids, Ceramide NP, Ceramide AP, Ceramide EOP, Phytosphingosine, Cholesterol, Linoleic Acid, Palmitic Acid, Oleic Acid, Isoceteth-20, Stearic Acid, Cetyl Phosphate, Arachidyl Alcohol, Behenyl Alcohol, Arachidyl Glucoside, Xanthan Gum, Pentylene Glycol, Triethanolamine, Citric Acid, Trisodium Ethylenediamine Disuccinate, Phenoxyethanol, Chlorphenesin', false, 93, 'https://m.media-amazon.com/images/I/51qXdWPIYBL._SL1500_.jpg', 'Sephora', 4.5, 45670),

('Round Lab', '1025 Dokdo Cream', 'moisturizer', 'Deep sea water cream', 22.00, 'USD', 'Water, Glycerin, Butylene Glycol, Cetyl Ethylhexanoate, Hydrogenated Poly(C6-14 Olefin), Cetearyl Alcohol, Glyceryl Stearate, PEG-100 Stearate, Deep Sea Water, 1,2-Hexanediol, Carbomer, Dimethicone, Panthenol, Arginine, Sodium Hyaluronate, Allantoin, Disodium EDTA, Ethylhexylglycerin, Tocopheryl Acetate', false, 91, 'https://m.media-amazon.com/images/I/51TuWYe9UbL._SL1500_.jpg', 'Olive Young', 4.6, 4560),

('iUNIK', 'Centella Calming Gel Cream', 'moisturizer', 'Lightweight centella gel cream', 18.00, 'USD', 'Centella Asiatica Leaf Water, Butylene Glycol, Glycerin, 1,2-Hexanediol, Tea Tree Leaf Water, Hydroxyacetophenone, Sodium Hyaluronate, Carbomer, Arginine, Allantoin, Madecassoside, Adenosine, Camellia Sinensis Leaf Extract, Betaine, Melaleuca Alternifolia Leaf Oil', true, 88, 'https://m.media-amazon.com/images/I/51MJVzAZnUL._SL1500_.jpg', 'YesStyle', 4.5, 3450),

('Vanicream', 'Daily Facial Moisturizer', 'moisturizer', 'Fragrance-free moisturizer for sensitive skin', 14.99, 'USD', 'Purified Water, Glycerin, Ceteareth-20, Cetearyl Alcohol, Caprylic/Capric Triglyceride, Squalane, Hyaluronic Acid, Ceramide NP, Ceramide AP, Ceramide EOP, Phytosphingosine, Cholesterol, Carbomer, Xanthan Gum, Dimethicone, Caprylyl Glycol, Disodium EDTA, Potassium Sorbate', false, 95, 'https://m.media-amazon.com/images/I/71HqD8YEBKL._SL1500_.jpg', 'Amazon', 4.6, 8970),

('Stratia', 'Liquid Gold', 'moisturizer', 'Ceramide-rich moisturizer for barrier repair', 27.00, 'USD', 'Water, Propanediol, Squalane, Caprylic/Capric Triglyceride, Cetyl Alcohol, Rosa Canina Fruit Oil, Hippophae Rhamnoides Fruit Oil, Niacinamide, Cholesterol, Ceramide NP, Tocopherol, Glycerin, Panthenol, Allantoin, Dimethicone, Cetearyl Alcohol, Ceteareth-20, Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Xanthan Gum, Phenoxyethanol, Ethylhexylglycerin', false, 93, 'https://m.media-amazon.com/images/I/51tWjJM-fLL._SL1500_.jpg', 'Stratia', 4.7, 5670),

('Soon Jung', '10 Free Moist Emulsion', 'moisturizer', 'Lightweight moisturizing emulsion', 13.00, 'USD', 'Water, Glycerin, Propanediol, Caprylic/Capric Triglyceride, Cetearyl Alcohol, Madecassoside, Glyceryl Stearate SE, Panthenol, 1,2-Hexanediol, Glyceryl Stearate, Stearic Acid, Carbomer, Arginine, Allantoin, Ethylhexylglycerin, Disodium EDTA, Camellia Sinensis Leaf Extract', false, 94, 'https://m.media-amazon.com/images/I/51HVXeAolTL._SL1200_.jpg', 'Olive Young', 4.6, 4560),

('Glow Recipe', 'Plum Plump Hyaluronic Cream', 'moisturizer', 'Plum and hyaluronic acid cream', 42.00, 'USD', 'Water, Propanediol, Glycerin, Squalane, Polyglyceryl-6 Stearate, Cetearyl Alcohol, Prunus Domestica Fruit Extract, Sodium Hyaluronate, Sodium Hyaluronate Crosspolymer, Silica, Polyglyceryl-6 Behenate, Jojoba Esters, Tocopherol, Sorbitan Stearate, Xanthan Gum, Carbomer, Aminomethyl Propanol, Phenoxyethanol, Ethylhexylglycerin, Fragrance', true, 87, 'https://m.media-amazon.com/images/I/51wVQ-GofTL._SL1500_.jpg', 'Sephora', 4.4, 3450),

('Aveeno', 'Calm + Restore Oat Gel Moisturizer', 'moisturizer', 'Sensitive skin gel moisturizer', 19.99, 'USD', 'Water, Glycerin, Dimethicone, Disteardimonium Hectorite, Isohexadecane, Avena Sativa Kernel Extract, Feverfew Extract, Niacinamide, Panthenol, Glycine Soja Oil, Aloe Barbadensis Leaf Juice, Allantoin, Disodium EDTA, Phenoxyethanol, Ethylhexylglycerin', false, 91, 'https://m.media-amazon.com/images/I/71hqYN0VQuL._SL1500_.jpg', 'Target', 4.5, 6780),

-- SUNSCREENS (15)
('Supergoop', 'Unseen Sunscreen SPF 40', 'sunscreen', 'Invisible primer-like sunscreen', 38.00, 'USD', 'Avobenzone 3%, Homosalate 8%, Octisalate 5%, Octocrylene 4%, Dimethicone, Water, Dimethicone/Vinyl Dimethicone Crosspolymer, Silica, Glycerin, Diethylhexyl 2,6-Naphthalate, Caprylyl Methicone, Butylene Glycol, Meadowfoam Estolide, Polyhydroxystearic Acid, Behenyl Alcohol, Isododecane, Phenoxyethanol, Camellia Sinensis Leaf Extract, Sodium Chloride, Tocopherol, Citric Acid', false, 85, 'https://m.media-amazon.com/images/I/61C1GBEgLJL._SL1500_.jpg', 'Sephora', 4.5, 23450),

('Biore', 'UV Aqua Rich Watery Essence SPF 50+', 'sunscreen', 'Japanese watery sunscreen', 15.00, 'USD', 'Water, Ethylhexyl Methoxycinnamate, Lauryl Methacrylate/Sodium Methacrylate Crosspolymer, Alcohol, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Glycerin, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Dimethicone, Ethylhexyl Triazone, Butylene Glycol, Dextrin Palmitate, Agar, Sodium Hyaluronate, Royal Jelly Extract, Arginine, Lysine, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Polysilicone-9, EDTA-2Na, BHT, Phenoxyethanol', false, 82, 'https://m.media-amazon.com/images/I/71t7BaKmPEL._SL1500_.jpg', 'Amazon', 4.4, 45670),

('Isntree', 'Hyaluronic Acid Watery Sun Gel SPF 50+', 'sunscreen', 'Korean watery gel sunscreen', 18.00, 'USD', 'Water, Dibutyl Adipate, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Ethylhexyl Triazone, Glycerin, Butyloctyl Salicylate, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Butylene Glycol, Niacinamide, Sodium Hyaluronate, Centella Asiatica Extract, 1,2-Hexanediol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Tromethamine, Carbomer, Xanthan Gum, Adenosine, Ethylhexylglycerin', false, 89, 'https://m.media-amazon.com/images/I/51d1hG8OfNL._SL1500_.jpg', 'YesStyle', 4.6, 5670),

('Beauty of Joseon', 'Relief Sun: Rice + Probiotics SPF 50+', 'sunscreen', 'Rice bran sunscreen', 16.00, 'USD', 'Water, Dibutyl Adipate, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Polymethylsilsesquioxane, Ethylhexyl Triazone, Niacinamide, Glycerin, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Butyloctyl Salicylate, Oryza Sativa Bran Extract, Oryza Sativa Bran Water, Lactobacillus Ferment, Propanediol, 1,2-Hexanediol, Caprylyl Methicone, Polyglyceryl-3 Methylglucose Distearate, Tromethamine, Carbomer, Acrylates/C10-30 Alkyl Acrylate Crosspolymer', false, 90, 'https://m.media-amazon.com/images/I/51R7W5T0-kL._SL1500_.jpg', 'Olive Young', 4.8, 12340),

('La Roche-Posay', 'Anthelios Melt-in Milk SPF 100', 'sunscreen', 'High SPF body sunscreen', 35.99, 'USD', 'Water, Homosalate 15%, Avobenzone 3%, Octisalate 5%, Octocrylene 7%, Oxybenzone 6%, Glycerin, Silica, Styrene/Acrylates Copolymer, Potassium Cetyl Phosphate, Tocopherol, Sodium Stearoyl Glutamate, Stearyl Alcohol, Phenoxyethanol, Caprylyl Glycol, Xanthan Gum, Disodium EDTA, Fragrance', true, 78, 'https://m.media-amazon.com/images/I/61dYq9G-mdL._SL1500_.jpg', 'Ulta', 4.5, 8970),

('Canmake', 'Mermaid Skin Gel UV SPF 50+', 'sunscreen', 'Japanese gel sunscreen', 11.00, 'USD', 'Water, Ethylhexyl Methoxycinnamate, Methyl Methacrylate Crosspolymer, BG, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Ethylhexyl Triazone, Glycerin, Pentylene Glycol, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Isohexadecane, Polysorbate 80, Xanthan Gum, Sodium Hyaluronate, Ethylhexylglycerin', false, 84, 'https://m.media-amazon.com/images/I/51YvPY9BXeL._SL1200_.jpg', 'Amazon', 4.4, 6780),

('Elta MD', 'UV Clear Broad-Spectrum SPF 46', 'sunscreen', 'Dermatologist-favorite sunscreen for acne-prone skin', 41.00, 'USD', 'Active Ingredients: Zinc Oxide 9%, Octinoxate 7.5%, Niacinamide, Hyaluronic Acid, Lactic Acid, Tocopheryl Acetate, Purified Water, Cyclomethicone, Octyldodecyl Neopentanoate, C12-15 Alkyl Benzoate, Sodium Hyaluronate, Oleth-3 Phosphate, Tocopheryl Acetate, Phenoxyethanol, Polyaminopropyl Biguanide', false, 89, 'https://m.media-amazon.com/images/I/61kzpkBX-vL._SL1500_.jpg', 'Dermstore', 4.5, 34560),

('Purito', 'Daily Go-To Sunscreen SPF 50+', 'sunscreen', 'Updated gentle sunscreen', 14.00, 'USD', 'Water, Dibutyl Adipate, Propanediol, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Polymethylsilsesquioxane, Ethylhexyl Triazone, Niacinamide, Glycerin, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Butyloctyl Salicylate, 1,2-Hexanediol, Caprylyl Methicone, Sodium Hyaluronate, Centella Asiatica Extract, Polyglyceryl-3 Methylglucose Distearate, Tromethamine, Carbomer, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Adenosine', false, 91, 'https://m.media-amazon.com/images/I/61BZrjLTsLL._SL1500_.jpg', 'Soko Glam', 4.6, 8970),

('Skin Aqua', 'Super Moisture Gel SPF 50+', 'sunscreen', 'Japanese moisture gel sunscreen', 12.00, 'USD', 'Water, Ethylhexyl Methoxycinnamate, BG, Isopropyl Palmitate, Methyl Methacrylate Crosspolymer, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Ethylhexyl Triazone, Glycerin, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Dimethicone, Xanthan Gum, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Sodium Hyaluronate, Ethylhexylglycerin, EDTA-2Na, Phenoxyethanol', false, 85, 'https://m.media-amazon.com/images/I/61s+K4ZDBWL._SL1500_.jpg', 'Amazon', 4.5, 12340),

('Krave Beauty', 'The Beet Shield SPF 50+', 'sunscreen', 'Chemical sunscreen with beet extract', 20.00, 'USD', 'Water, Dibutyl Adipate, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Propanediol, C12-15 Alkyl Benzoate, Polymethylsilsesquioxane, Polyglyceryl-3 Methylglucose Distearate, Ethylhexyl Triazone, Glycerin, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Butyloctyl Salicylate, Silica, Beta Vulgaris Root Extract, Niacinamide, 1,2-Hexanediol, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Xanthan Gum, Tromethamine', false, 90, 'https://m.media-amazon.com/images/I/51VkJR4UJUL._SL1500_.jpg', 'Krave Beauty', 4.5, 4560),

('Missha', 'All Around Safe Block Essence Sun SPF 45', 'sunscreen', 'Lightweight Korean sunscreen', 14.00, 'USD', 'Water, Ethylhexyl Methoxycinnamate, Ethylhexyl Salicylate, Glycerin, Butylene Glycol, Titanium Dioxide, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Niacinamide, Cyclopentasiloxane, Cetearyl Alcohol, Sodium Hyaluronate, Aloe Barbadensis Leaf Extract, Tocopheryl Acetate, Phenoxyethanol, Fragrance', true, 82, 'https://m.media-amazon.com/images/I/61G5rRoGQ7L._SL1500_.jpg', 'YesStyle', 4.3, 5670),

('Round Lab', 'Birch Juice Moisturizing Sun Cream SPF 50+', 'sunscreen', 'Birch sap sunscreen', 18.00, 'USD', 'Water, Dibutyl Adipate, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Propanediol, Polymethylsilsesquioxane, Ethylhexyl Triazone, Glycerin, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Butyloctyl Salicylate, Betula Platyphylla Japonica Juice, Niacinamide, 1,2-Hexanediol, Sodium Hyaluronate, Carbomer, Allantoin, Adenosine, Xanthan Gum', false, 91, 'https://m.media-amazon.com/images/I/51d-RmIf5HL._SL1500_.jpg', 'Olive Young', 4.7, 6780),

('Bondi Sands', 'Hydra UV Protect SPF 50+ Face Fluid', 'sunscreen', 'Australian sunscreen', 19.99, 'USD', 'Aqua, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Ethylhexyl Triazone, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Glycerin, Butyloctyl Salicylate, Propanediol, Diisopropyl Adipate, C12-15 Alkyl Benzoate, Cetearyl Alcohol, Niacinamide, Sodium Hyaluronate, Cetearyl Glucoside, Xanthan Gum, Phenoxyethanol, Ethylhexylglycerin', false, 87, 'https://m.media-amazon.com/images/I/61a9kPaLhDL._SL1500_.jpg', 'Target', 4.4, 3450),

('Anessa', 'Perfect UV Sunscreen Skincare Milk SPF 50+', 'sunscreen', 'Japanese sport sunscreen', 35.00, 'USD', 'Water, Zinc Oxide, Ethylhexyl Methoxycinnamate, Alcohol Denat, Isopropyl Palmitate, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Methyl Methacrylate Crosspolymer, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Butylene Glycol, Glycerin, Sodium Hyaluronate, Rosa Roxburghii Fruit Extract, Tocopherol, Phenoxyethanol, Fragrance', true, 84, 'https://m.media-amazon.com/images/I/61HjKcOpURL._SL1500_.jpg', 'Amazon', 4.6, 8970),

('COSRX', 'Aloe Soothing Sun Cream SPF 50+', 'sunscreen', 'Aloe-based soothing sunscreen', 16.00, 'USD', 'Water, Ethylhexyl Methoxycinnamate, Aloe Barbadensis Leaf Extract, Ethylhexyl Salicylate, Glycerin, Butylene Glycol, Titanium Dioxide, Bis-Ethylhexyloxyphenol Methoxyphenyl Triazine, Diethylamino Hydroxybenzoyl Hexyl Benzoate, Cetearyl Alcohol, Panthenol, Allantoin, Sodium Hyaluronate, 1,2-Hexanediol, Carbomer, Tromethamine', false, 88, 'https://m.media-amazon.com/images/I/61pnMlMLbVL._SL1500_.jpg', 'Soko Glam', 4.5, 4560),

-- EYE CREAMS (5)
('CeraVe', 'Eye Repair Cream', 'eye_cream', 'Ceramide eye cream for dark circles', 18.99, 'USD', 'Aqua, Glycerin, Cetyl Alcohol, Caprylic/Capric Triglyceride, Caffeine, Niacinamide, Cetearyl Alcohol, PEG-100 Stearate, Glyceryl Stearate, Ceramide NP, Ceramide AP, Ceramide EOP, Phytosphingosine, Cholesterol, Sodium Hyaluronate, Dimethicone, Panthenol, Sodium Lauroyl Lactylate, Behentrimonium Methosulfate, Carbomer, Xanthan Gum, Phenoxyethanol, Disodium EDTA, Tocopherol', false, 91, 'https://m.media-amazon.com/images/I/71oXKKoAM8L._SL1500_.jpg', 'Amazon', 4.4, 8970),

('The Ordinary', 'Caffeine Solution 5% + EGCG', 'eye_cream', 'Caffeine serum for puffiness', 7.20, 'USD', 'Aqua, Caffeine, Maltodextrin, Glycerin, Propanediol, Epigallocatechin Gallatyl Glucoside, Gallyl Glucoside, Hyaluronic Acid, Oxidized Glutathione, Melanin, Glycine Soja Seed Extract, Urea, Pentylene Glycol, Hydroxyethylcellulose, Xanthan Gum, Lactic Acid, Dehydroacetic Acid, Trisodium Ethylenediamine Disuccinate, Propyl Gallate, Dimethyl Isosorbide, Benzyl Alcohol, 1,2-Hexanediol, Ethylhexylglycerin, Caprylyl Glycol', false, 88, 'https://m.media-amazon.com/images/I/61GZLfxDNVL._SL1500_.jpg', 'Sephora', 4.2, 23450),

('Kiehl''s', 'Creamy Eye Treatment with Avocado', 'eye_cream', 'Hydrating avocado eye cream', 34.00, 'USD', 'Aqua, Persea Gratissima Oil, Butylene Glycol, Sodium PCA, Beta-Carotene, Glycerin, Shea Butter, PEG-20 Stearate, Cetyl Alcohol, Lecithin, Glyceryl Stearate, Tocopheryl Acetate, Acrylates/C10-30 Alkyl Acrylate Crosspolymer, Carbomer, Sodium Hydroxide, Phenoxyethanol, Fragrance', true, 86, 'https://m.media-amazon.com/images/I/61eWxLLvTXL._SL1500_.jpg', 'Sephora', 4.5, 12340),

('Innisfree', 'Green Tea Seed Eye Cream', 'eye_cream', 'Green tea eye cream', 24.00, 'USD', 'Water, Butylene Glycol, Glycerin, Squalane, Cetyl Alcohol, Caprylic/Capric Triglyceride, Dimethicone, Camellia Sinensis Seed Oil, Camellia Sinensis Seed Extract, Camellia Sinensis Leaf Extract, Sodium Hyaluronate, Ceramide NP, Niacinamide, Adenosine, Panthenol, Allantoin, Carbomer, Xanthan Gum, Phenoxyethanol, Ethylhexylglycerin, Fragrance', true, 86, 'https://m.media-amazon.com/images/I/51N-4Tq7TdL._SL1500_.jpg', 'Sephora', 4.3, 3450),

('Mizon', 'Snail Repair Eye Cream', 'eye_cream', 'Snail mucin eye cream', 13.00, 'USD', 'Snail Secretion Filtrate, Glycerin, Butylene Glycol, Cetyl Ethylhexanoate, Niacinamide, Cyclopentasiloxane, Sodium Hyaluronate, Adenosine, EGF, Arginine, Carbomer, Phenoxyethanol, Ethylhexylglycerin, Allantoin', false, 89, 'https://m.media-amazon.com/images/I/51YZq6WYLNL._SL1500_.jpg', 'YesStyle', 4.4, 5670),

-- MASKS (10)
('Laneige', 'Water Sleeping Mask', 'mask', 'Overnight hydrating mask', 28.00, 'USD', 'Water, Butylene Glycol, Cyclopentasiloxane, Glycerin, Cyclohexasiloxane, Trehalose, Sodium Hyaluronate, Hydrolyzed Collagen, Chenopodium Quinoa Seed Extract, Opuntia Ficus-Indica Extract, Beta-Glucan, Glycyrrhiza Glabra Root Extract, Squalane, Dimethicone, Dimethicone/Vinyl Dimethicone Crosspolymer, Carbomer, Tromethamine, Phenoxyethanol, Fragrance, Blue 1', true, 85, 'https://m.media-amazon.com/images/I/51kxWdGI3NL._SL1500_.jpg', 'Sephora', 4.5, 23450),

('Glow Recipe', 'Watermelon Glow Sleeping Mask', 'mask', 'Watermelon AHA sleeping mask', 45.00, 'USD', 'Water, Glycerin, Propanediol, Citrullus Lanatus Fruit Extract, Hyaluronic Acid, AHA Blend, Amino Acids, Peony Root Extract, Betaine, Sodium Hyaluronate, Niacinamide, Adenosine, Potassium Azeloyl Diglycinate, Trehalose, Allantoin, Xanthan Gum, Phenoxyethanol, Ethylhexylglycerin, Fragrance', true, 84, 'https://m.media-amazon.com/images/I/51OPMXS8-QL._SL1500_.jpg', 'Sephora', 4.4, 8970),

('COSRX', 'Ultimate Nourishing Rice Overnight Spa Mask', 'mask', 'Rice sleeping mask', 18.00, 'USD', 'Oryza Sativa Bran Water, Butylene Glycol, Glycerin, Niacinamide, Betaine, 1,2-Hexanediol, Oryza Sativa Bran Extract, Oryza Sativa Bran Oil, Sodium Hyaluronate, Allantoin, Adenosine, Xanthan Gum, Ethylhexylglycerin', false, 91, 'https://m.media-amazon.com/images/I/61nLm9eV7WL._SL1500_.jpg', 'Soko Glam', 4.6, 4560),

('Origins', 'Drink Up Intensive Overnight Mask', 'mask', 'Hydrating overnight mask', 32.00, 'USD', 'Water, Glycerin, Caprylic/Capric Triglyceride, Butylene Glycol, Dimethicone, Avocado Oil, Sodium Hyaluronate, Trehalose, Algae Extract, Aloe Barbadensis Leaf Juice, Sodium Stearoyl Glutamate, Carbomer, Phenoxyethanol, Ethylhexylglycerin, Fragrance', true, 86, 'https://m.media-amazon.com/images/I/51KXHcE6ZXL._SL1500_.jpg', 'Sephora', 4.4, 5670),

('I''m From', 'Mugwort Mask', 'mask', 'Calming mugwort wash-off mask', 30.00, 'USD', 'Artemisia Princeps Leaf Powder, Water, Glycerin, Butylene Glycol, Kaolin, Bentonite, Caprylyl Methicone, 1,2-Hexanediol, Allantoin, Panthenol, Sodium Hyaluronate, Disodium EDTA', false, 92, 'https://m.media-amazon.com/images/I/51FaLj-LQFL._SL1500_.jpg', 'Soko Glam', 4.7, 6780),

('Innisfree', 'Super Volcanic Pore Clay Mask 2X', 'mask', 'Deep cleansing clay mask', 15.00, 'USD', 'Water, Glycerin, Kaolin, Bentonite, Titanium Dioxide, Jeju Volcanic Ash, Cetyl Ethylhexanoate, Propanediol, Butylene Glycol, Niacinamide, Allantoin, Sodium Hyaluronate, Carbomer, Phenoxyethanol, Ethylhexylglycerin, Fragrance', true, 85, 'https://m.media-amazon.com/images/I/61E+YHmK9OL._SL1500_.jpg', 'Sephora', 4.3, 8970),

('Summer Fridays', 'Jet Lag Mask', 'mask', 'Hydrating cream mask', 48.00, 'USD', 'Water, Glycerin, Caprylic/Capric Triglyceride, Cetyl Alcohol, Squalane, Glyceryl Stearate, Chondrus Crispus Extract, Sodium Hyaluronate, Niacinamide, Allantoin, Tocopherol, Panthenol, Sodium PCA, Ceramide NP, Phenoxyethanol, Ethylhexylglycerin, Xanthan Gum, Fragrance', true, 87, 'https://m.media-amazon.com/images/I/51Hwa4RCDCL._SL1500_.jpg', 'Sephora', 4.5, 7890),

('Herbivore', 'Blue Tansy Resurfacing Clarity Mask', 'mask', 'Blue tansy clarifying mask', 48.00, 'USD', 'Aloe Barbadensis Leaf Juice, Kaolin, Glycerin, White Willow Bark Extract, Fruit Enzymes, Blue Tansy Essential Oil, Squalane, Allantoin, Sodium Hyaluronate, Tocopherol, Xanthan Gum', true, 84, 'https://m.media-amazon.com/images/I/51x-C8xZ7qL._SL1500_.jpg', 'Sephora', 4.2, 3450),

('Farmacy', 'Honey Potion Renewing Antioxidant Hydration Mask', 'mask', 'Warming honey mask', 38.00, 'USD', 'Honey, Glycerin, PEG-7 Glyceryl Cocoate, Squalane, Propanediol, Royal Jelly, Propolis Extract, Echinacea Purpurea Extract, Hyaluronic Acid, Vitamin B3, Allantoin, Panthenol, Tocopherol, Phenoxyethanol, Ethylhexylglycerin', false, 89, 'https://m.media-amazon.com/images/I/51A2NWkILTL._SL1500_.jpg', 'Sephora', 4.4, 6780),

('Kiehl''s', 'Rare Earth Deep Pore Cleansing Masque', 'mask', 'Amazonian clay mask', 38.00, 'USD', 'Water, Kaolin, Bentonite, Glycerin, Aloe Barbadensis Leaf Juice, Butylene Glycol, Oat Flour, Montmorillonite, Titanium Dioxide, Chamomilla Recutita Flower Extract, Allantoin, Phenoxyethanol, Carbomer, Sodium Hydroxide', false, 87, 'https://m.media-amazon.com/images/I/61gRo3YoxML._SL1500_.jpg', 'Sephora', 4.3, 12340);

-- ============================================================================
-- VERIFICATION
-- ============================================================================

SELECT
    category,
    COUNT(*) as count
FROM products
GROUP BY category
ORDER BY count DESC;

SELECT 'Total products:' as info, COUNT(*) as count FROM products;
SELECT 'Products with Amazon images:' as info, COUNT(*) as count FROM products WHERE image_url LIKE '%amazon%';
